/*
 Navicat Premium Data Transfer

 Source Server         : node
 Source Server Type    : MySQL
 Source Server Version : 50727
 Source Host           : localhost:3306
 Source Schema         : qq

 Target Server Type    : MySQL
 Target Server Version : 50727
 File Encoding         : 65001

 Date: 24/03/2020 10:56:04
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for list
-- ----------------------------
DROP TABLE IF EXISTS `list`;
CREATE TABLE `list`  (
  `songname` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '歌曲名称',
  `type_id` int(11) NOT NULL COMMENT '分类id',
  `singer` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '歌手名字',
  `rank` int(255) NOT NULL COMMENT '排名顺序'
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_bin ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of list
-- ----------------------------
INSERT INTO `list` VALUES ('情深深雨濛濛', 28, '杨胖雨', 3);
INSERT INTO `list` VALUES ('我走后', 28, '小咪', 4);
INSERT INTO `list` VALUES ('余情未了', 28, '魏新雨', 5);
INSERT INTO `list` VALUES ('多年以后', 28, '大欢', 6);
INSERT INTO `list` VALUES ('孤独', 28, '是你大哥阿', 7);
INSERT INTO `list` VALUES ('那女孩对我说 (完整版)', 28, 'Uu', 8);
INSERT INTO `list` VALUES ('Batte Forte凤舞九天 (DJ弹鼓版)', 28, '承利', 9);
INSERT INTO `list` VALUES ('天下有情人 (国语版)', 28, '童珺', 10);
INSERT INTO `list` VALUES ('把孤独当作晚餐', 28, 'MC画词戏子', 11);
INSERT INTO `list` VALUES ('云水谣', 28, 'en', 12);
INSERT INTO `list` VALUES ('迷人的危险', 28, '馅儿/neko', 13);
INSERT INTO `list` VALUES ('归去来兮', 28, '曼殊', 14);
INSERT INTO `list` VALUES ('纵歌万里游', 28, '叶洛洛· “我为家乡写情诗”主题曲', 15);
INSERT INTO `list` VALUES ('一百万个可能', 28, '艾辰', 16);
INSERT INTO `list` VALUES ('17岁', 28, '梦涵', 17);
INSERT INTO `list` VALUES ('从前的我快乐过', 28, '蒋雪儿', 18);
INSERT INTO `list` VALUES ('撕夜', 28, '王恰恰', 19);
INSERT INTO `list` VALUES ('十一', 28, '穆哲熙', 21);
INSERT INTO `list` VALUES ('拜拜', 28, '浙音4811', 20);
INSERT INTO `list` VALUES ('归寻', 28, '等什么君', 22);
INSERT INTO `list` VALUES ('只要你还需要我', 28, '小曼', 23);
INSERT INTO `list` VALUES ('酒空人醒', 28, '李冠霖', 25);
INSERT INTO `list` VALUES ('野花香', 28, '莫斯满/老猫', 24);
INSERT INTO `list` VALUES ('超级英雄狂想曲', 28, '龚十一', 26);
INSERT INTO `list` VALUES ('洪荒之力 (抖音热播)', 28, '8先生/李仕伟', 27);
INSERT INTO `list` VALUES ('一世薄凉', 28, '海来阿木', 28);
INSERT INTO `list` VALUES ('琵琶语', 28, '糯米Nomi', 29);
INSERT INTO `list` VALUES ('时间', 28, '贺一航', 30);
INSERT INTO `list` VALUES ('心如止水 (女声完整版)', 28, '喻言家', 31);
INSERT INTO `list` VALUES ('相遇那么美', 28, '魏新雨', 32);
INSERT INTO `list` VALUES ('成全', 28, '蓝心羽', 33);
INSERT INTO `list` VALUES ('直觉 (女版)', 28, '王珂珂', 34);
INSERT INTO `list` VALUES ('四块五 (DJ咚鼓版)', 28, '浪子康/豪大大', 35);
INSERT INTO `list` VALUES ('我愿意平凡的陪在你身旁 (DjYaha)', 28, '王七七', 36);
INSERT INTO `list` VALUES ('该不会忘了吧', 28, '马晓晨', 37);
INSERT INTO `list` VALUES ('戏影', 28, '彭十六', 38);
INSERT INTO `list` VALUES ('【温宁】赤子', 28, '于斌', 39);
INSERT INTO `list` VALUES ('停摆 (女版)', 28, '小曼', 40);
INSERT INTO `list` VALUES ('黎明前的黑暗', 28, '孟颖', 41);
INSERT INTO `list` VALUES ('我曾 (Cover 隔壁老樊)', 28, '馅儿', 42);
INSERT INTO `list` VALUES ('选择失忆 (DJ咚鼓版)', 28, '季彦霖', 43);
INSERT INTO `list` VALUES ('画者', 28, '鱼香婆婆', 44);
INSERT INTO `list` VALUES ('最寂寞的寂寞', 28, '金南玲', 47);
INSERT INTO `list` VALUES ('爱过了也伤过了', 28, '苏谭谭', 45);
INSERT INTO `list` VALUES ('过期的誓言', 28, '小二哥', 46);
INSERT INTO `list` VALUES ('柒月', 28, '排骨教主', 49);
INSERT INTO `list` VALUES ('人间城', 28, '王贰浪', 48);
INSERT INTO `list` VALUES ('绝不会放过', 28, '徐聪', 50);
INSERT INTO `list` VALUES ('哥们永远', 28, 'Mr.丁/大壮', 52);
INSERT INTO `list` VALUES ('Read All About It (Original Mix)', 28, '泽亦龙', 51);
INSERT INTO `list` VALUES ('通透', 28, '陈亦云', 53);
INSERT INTO `list` VALUES ('波妞和宗介 (抖音版)', 28, '精彩苏刚/陈丙', 54);
INSERT INTO `list` VALUES ('广寒宫', 28, '丸子呦', 55);
INSERT INTO `list` VALUES ('大暑', 28, '音阙诗听/李佳思', 57);
INSERT INTO `list` VALUES ('唯你之光', 28, 'Vk/汐音社', 56);
INSERT INTO `list` VALUES ('错的结果', 28, '唐古', 58);
INSERT INTO `list` VALUES ('天蓬大元帅', 28, '小倩', 59);
INSERT INTO `list` VALUES ('圈住你', 28, '一口甜', 61);
INSERT INTO `list` VALUES ('去终南', 28, '半阳', 60);
INSERT INTO `list` VALUES ('向前走', 28, '龙梅子· 电影《陌上有信》推广曲', 62);
INSERT INTO `list` VALUES ('安暖相伴', 28, '金艾娜/望海高歌', 63);
INSERT INTO `list` VALUES ('其实我们都有故事', 28, '樊少华', 64);
INSERT INTO `list` VALUES ('假如', 28, '伊林', 65);
INSERT INTO `list` VALUES ('不让（盗墓笔记·重启）', 28, '五音Jw/陆深', 67);
INSERT INTO `list` VALUES ('我终究还是爱你的', 28, '魏新雨', 66);
INSERT INTO `list` VALUES ('以爱之名', 28, '麓七· “以爱之名”活动主题曲', 68);
INSERT INTO `list` VALUES ('你笑起来真好看 (正版授权)', 28, '叶嘉', 69);
INSERT INTO `list` VALUES ('回家的路', 28, '大欢', 70);
INSERT INTO `list` VALUES ('恋爱脑少女', 28, '赵露思· 《天雷一部之春花秋月》电视剧片头曲', 71);
INSERT INTO `list` VALUES ('红尘情痴', 28, '王琪', 72);
INSERT INTO `list` VALUES ('假装快乐', 28, '曲肖冰', 73);
INSERT INTO `list` VALUES ('愿', 28, '艾辰', 74);
INSERT INTO `list` VALUES ('画师', 28, '夏婉安', 75);
INSERT INTO `list` VALUES ('三杯酒', 28, '陈雅森', 76);
INSERT INTO `list` VALUES ('我叫安琪拉', 28, '向熙', 77);
INSERT INTO `list` VALUES ('Sweet But Psycho(车载4)', 28, '7妹/琦妹儿', 78);
INSERT INTO `list` VALUES ('别知己', 28, '海来阿木', 79);
INSERT INTO `list` VALUES ('爱情总会败给时间', 28, '贺一航', 80);
INSERT INTO `list` VALUES ('洪荒之力 + 黎明前的黑暗 (DJ阿超 Remix)', 28, 'DJ阿超', 81);
INSERT INTO `list` VALUES ('抱歉，不懂我的人', 28, '鱼大仙儿', 83);
INSERT INTO `list` VALUES ('一去不回来', 28, '张冬玲', 84);
INSERT INTO `list` VALUES ('把孤独当作晚餐', 28, 'MC画词戏子', 82);
INSERT INTO `list` VALUES ('我就喜欢宅在家', 28, '叶洛洛/妖蝠', 85);
INSERT INTO `list` VALUES ('晚安 (DJ弹鼓版)', 28, '浪子康/豪大大', 86);
INSERT INTO `list` VALUES ('洪荒之力电摇 (抖音版)', 28, 'DJ奶小深/DJ蒋先生/普先森', 87);
INSERT INTO `list` VALUES ('情侣之间', 28, '蒋家驹（蒋蒋）', 88);
INSERT INTO `list` VALUES ('旧人', 28, '安苏羽', 89);
INSERT INTO `list` VALUES ('Coming Home (改版)', 28, '新旭', 90);
INSERT INTO `list` VALUES ('光明', 28, '张茜', 91);
INSERT INTO `list` VALUES ('相思灯', 28, '林维', 92);
INSERT INTO `list` VALUES ('i don\'t wanna see u anymore 2019', 28, 'NINEONE #', 93);
INSERT INTO `list` VALUES ('天黑了（Cause夜、萤火虫和你)', 28, '夏婉安', 94);
INSERT INTO `list` VALUES ('鳌拜鳌拜鳌拜拜 (Original Mix)', 28, '南辞/唐总', 95);
INSERT INTO `list` VALUES ('来自天堂的魔鬼', 28, '杨又歌', 96);
INSERT INTO `list` VALUES ('不错过', 28, '夏婉安', 97);
INSERT INTO `list` VALUES ('悠殇叹', 28, '阿悠悠', 98);
INSERT INTO `list` VALUES ('醉仙美', 28, '徐聪', 99);
INSERT INTO `list` VALUES ('解忧', 29, '张靓颖· 《宸汐缘》电视剧女主情感主题曲', 3);
INSERT INTO `list` VALUES ('当你孤单你会想起谁', 29, '刘宪华 (Henry)· 《一条狗的使命2》电影中国区推广曲', 4);
INSERT INTO `list` VALUES ('无愧', 29, 'R1SE· 《上海堡垒》电影片尾主题曲', 5);
INSERT INTO `list` VALUES ('Another Day', 29, '먼데이 키즈 (Monday Kiz)/펀치 (PUNCH)· 《德鲁纳酒店》韩剧插曲', 6);
INSERT INTO `list` VALUES ('今夜我属于爱情', 29, '张学友/Beyoncé· 《狮子王》全球唯一国际版主题曲', 7);
INSERT INTO `list` VALUES ('今后我与自己流浪', 29, '张碧晨· 《哪吒之魔童降世》电影片尾曲', 8);
INSERT INTO `list` VALUES ('是缘', 29, '杨宗纬· 《宸汐缘》电视剧片头主题曲', 9);
INSERT INTO `list` VALUES ('鸟语林', 29, '双笙· 《宸汐缘》电视剧插曲', 11);
INSERT INTO `list` VALUES ('【魏无羡】曲尽陈情', 29, '肖战', 10);
INSERT INTO `list` VALUES ('相信你的人', 29, '陈奕迅· 《银河补习班》电影推广曲', 12);
INSERT INTO `list` VALUES ('耿', 29, '汪苏泷· 《最好的我们》电影毕业季主题曲', 13);
INSERT INTO `list` VALUES ('如果当时', 29, '胡夏· 《上海堡垒》电影推广曲', 14);
INSERT INTO `list` VALUES ('나의 어깨에 기대어요 (Lean on me)', 29, '10cm (십센치)· 《德鲁纳酒店》韩剧插曲', 15);
INSERT INTO `list` VALUES ('银河里最像的人', 29, '邓超· 《银河补习班》电影主题曲', 17);
INSERT INTO `list` VALUES ('清平乐', 29, '火箭少女101紫宁· 《长安十二时辰》电视剧主题推广曲', 16);
INSERT INTO `list` VALUES ('【蓝忘机】不忘', 29, '王一博', 19);
INSERT INTO `list` VALUES ('【主题曲】无羁（合唱版）', 29, '肖战/王一博', 18);
INSERT INTO `list` VALUES ('我只喜欢你', 29, '胡夏· 《我只喜欢你》影视剧主题曲', 20);
INSERT INTO `list` VALUES ('天空之外', 29, '弦子· 《陪你到世界之巅》电视剧片尾曲', 22);
INSERT INTO `list` VALUES ('哪吒', 29, 'GAI/大痒痒· 《哪吒之魔童降世》电影主题曲', 21);
INSERT INTO `list` VALUES ('【主题曲】无羁（ 周笔畅 特别版 ）', 29, '周笔畅', 23);
INSERT INTO `list` VALUES ('WOW', 29, 'MAMAMOO (마마무)· 《请输入搜索词：WWW》韩剧插曲', 25);
INSERT INTO `list` VALUES ('时光尽头', 29, '娜扎· 《归还世界给你》电视剧沈忆恩人物曲', 24);
INSERT INTO `list` VALUES ('Fall in Luv', 29, '刘宪华 (Henry)· 《新入史官具海玲》韩剧插曲', 26);
INSERT INTO `list` VALUES ('Can You Feel the Love Tonight', 29, 'Beyoncé/Donald Glover/Billy Eichner/Seth Rogen· 《狮子王》电影插曲', 27);
INSERT INTO `list` VALUES ('课间进行曲', 29, '阿肆· 《少年派》电视剧插曲', 28);
INSERT INTO `list` VALUES ('路过人间', 29, '郁可唯· 《我们与恶的距离》电视剧插曲', 30);
INSERT INTO `list` VALUES ('云上的傻瓜', 29, '陆虎· 《宸汐缘》电视剧插曲', 29);
INSERT INTO `list` VALUES ('最燃的冒险', 29, '王一博· 《陪你到世界之巅》电视剧主题曲', 31);
INSERT INTO `list` VALUES ('谢谢你走在我前面', 29, '梁咏琪· 《小Q》电影主题曲', 32);
INSERT INTO `list` VALUES ('短歌行', 29, '萨顶顶· 《长安十二时辰》主题推广曲', 33);
INSERT INTO `list` VALUES ('长安诀', 29, '汪苏泷· 《长安十二时辰》电视剧主题推广曲', 35);
INSERT INTO `list` VALUES ('我比从前想你了', 29, '毕书尽· 《我们不能是朋友》电视剧片尾曲', 34);
INSERT INTO `list` VALUES ('【温宁】赤子', 29, '于斌', 36);
INSERT INTO `list` VALUES ('兄弟不怀疑', 29, '刘德华/古天乐· 《扫毒2》主题曲', 37);
INSERT INTO `list` VALUES ('打破沉默', 29, '杨紫/任贤齐/欧阳靖· 《沉默的证人》电影主题曲', 38);
INSERT INTO `list` VALUES ('都是夜归人', 29, '阿云嘎/郑云龙· 《深夜食堂》电影片尾曲', 39);
INSERT INTO `list` VALUES ('没资格难过', 29, '张信哲· 《跳舞吧！大象》电影片尾曲', 40);
INSERT INTO `list` VALUES ('未完成的瞬间', 29, '李宏毅· 《天雷一部之春花秋月》电视剧片尾曲', 41);
INSERT INTO `list` VALUES ('【插曲】意难平', 29, '银临', 42);
INSERT INTO `list` VALUES ('【温情】疏林如有诉', 29, '高秋梓', 43);
INSERT INTO `list` VALUES ('小至', 29, '郁可唯/李治廷· 《白发》电视剧主题曲', 44);
INSERT INTO `list` VALUES ('【主题曲】无羁（肖战 独唱版）', 29, '肖战', 45);
INSERT INTO `list` VALUES ('追寻年少的光', 29, '林宥嘉/郁可唯· 《流淌的美好时光》电视剧主题曲', 47);
INSERT INTO `list` VALUES ('【蓝曦臣】不由', 29, '刘海宽', 46);
INSERT INTO `list` VALUES ('心锁', 29, '金润吉· 《白发》电视剧插曲', 48);
INSERT INTO `list` VALUES ('若雪', 29, '李治廷· 《白发》电视剧片尾曲', 49);
INSERT INTO `list` VALUES ('小情书', 29, '范世錡· 《追球》电视剧齐景浩角色曲', 50);
INSERT INTO `list` VALUES ('Spirit (From Disney\'s \"The Lion King\")', 29, 'Beyoncé', 51);
INSERT INTO `list` VALUES ('恋爱脑少女', 29, '赵露思· 《天雷一部之春花秋月》电视剧片头曲', 52);
INSERT INTO `list` VALUES ('I Know You Know', 29, '李治廷· 《我的真朋友》电视剧主题曲', 53);
INSERT INTO `list` VALUES ('海の幽霊 (海之幽灵)', 29, '米津玄師 (よねづ けんし)· 《海兽之子》动画电影主题曲', 54);
INSERT INTO `list` VALUES ('Forward Motion (From The Original Motion Picture “Late Night”|Explicit)', 29, 'Daya', 56);
INSERT INTO `list` VALUES ('追光的你 (男生版)', 29, '范世錡/黄圣池/朱元冰/李汶翰/李希侃· 《追球》电视剧主题曲', 55);
INSERT INTO `list` VALUES ('一双翅膀', 29, '鞠婧祎· 《请赐我一双翅膀》电视剧片尾曲', 57);
INSERT INTO `list` VALUES ('秣马', 29, '阿云嘎· 《九州缥缈录》电视剧主题曲', 58);
INSERT INTO `list` VALUES ('R.1.S.E', 29, 'R1SE· 《黑衣人：全球追缉》电影中国区主题推广曲', 59);
INSERT INTO `list` VALUES ('失物招领', 29, '郭一凡· 《动物管理局》网络剧告白版插曲', 60);
INSERT INTO `list` VALUES ('忘忧', 29, '张雪迎· 《白发》电视剧片尾曲', 61);
INSERT INTO `list` VALUES ('Taste', 29, 'Sonny Rey· 《带着爸爸去留学》电视剧插曲', 63);
INSERT INTO `list` VALUES ('【主题曲】无羁（王一博 独唱版）', 29, '王一博', 64);
INSERT INTO `list` VALUES ('Can You Hear', 29, '谭嘉仪· 《白色强人》电视剧插曲', 62);
INSERT INTO `list` VALUES ('Circle of Life/Nants\' Ingonyama', 29, 'Lindiwe Mkhize/Lebo M.· 《狮子王》电影插曲', 65);
INSERT INTO `list` VALUES ('真夏の夜の匂いがする (仲夏夜的气息)', 29, 'あいみょん· 《天国餐馆》日剧主题曲', 66);
INSERT INTO `list` VALUES ('Never let you go', 29, '萨吉· 《我只喜欢你》电视剧片尾曲', 67);
INSERT INTO `list` VALUES ('你', 29, '印子月· 《暗恋·橘生淮南》网剧主题曲', 68);
INSERT INTO `list` VALUES ('最好的我们', 29, '陈飞宇· 《最好的我们》电影同名主题曲', 69);
INSERT INTO `list` VALUES ('逆风', 29, '毛不易· 《筑梦情缘》电视剧男主情感主题曲', 70);
INSERT INTO `list` VALUES ('黑马', 29, '于文文· 《我的真朋友》电视剧插曲', 71);
INSERT INTO `list` VALUES ('生如狂澜', 29, '侯明昊/成毅/张博宇· 《怒海潜沙&秦岭神树》电视剧片尾曲', 72);
INSERT INTO `list` VALUES ('我们很好', 29, '林俊杰· 《少年的你》电影主题曲', 73);
INSERT INTO `list` VALUES ('一首情歌的时间', 29, '印子月· 《致我们暖暖的小时光》网络剧插曲', 74);
INSERT INTO `list` VALUES ('清平乐', 29, '刘珂矣· 《长安十二时辰》电视剧主题推广曲特别版', 75);
INSERT INTO `list` VALUES ('Speechless (Full)', 29, 'Naomi Scott· 《阿拉丁》电影插曲', 76);
INSERT INTO `list` VALUES ('拙慕', 29, '周深· 《爵迹临界天下》网络剧插曲', 77);
INSERT INTO `list` VALUES ('无妨', 29, '孙楠· 《破冰行动》电视剧主题曲', 78);
INSERT INTO `list` VALUES ('彼时', 29, '张碧晨· 《我的真朋友》电视剧插曲', 79);
INSERT INTO `list` VALUES ('向前走', 29, '龙梅子· 电影《陌上有信》推广曲', 80);
INSERT INTO `list` VALUES ('如果', 29, '弦子· 《我心深触》电视剧主题曲', 81);
INSERT INTO `list` VALUES ('Hakuna Matata', 29, 'Billy Eichner/Seth Rogen/JD McCrary/Donald Glover· 《狮子王》电影插曲', 83);
INSERT INTO `list` VALUES ('조금 더 외로워지겠지 (会更加孤独的)', 29, '김나영 (金娜英)· 《请输入搜索词：WWW》韩剧插曲', 84);
INSERT INTO `list` VALUES ('红尘微烫', 29, '陆翊· 《白发》电视剧插曲', 82);
INSERT INTO `list` VALUES ('藏不住的心跳', 29, '朱主爱· 《我只喜欢你》影视剧片头曲', 85);
INSERT INTO `list` VALUES ('无念', 29, '张靓颖· 《筑梦情缘》电视剧女主情感主题曲', 87);
INSERT INTO `list` VALUES ('最好的故事', 29, '毕书尽· 《我的真朋友》电视剧插曲', 86);
INSERT INTO `list` VALUES ('在你身边', 29, '胡莎莎· 《请赐我一双翅膀》电视剧插曲', 88);
INSERT INTO `list` VALUES ('昨日少年', 29, '摩登兄弟· 《企鹅公路》电影少年版中文主题曲', 89);
INSERT INTO `list` VALUES ('最相爱的朋友', 29, '马栗· 《我只喜欢你》影视剧插曲', 90);
INSERT INTO `list` VALUES ('青春大满贯', 29, '胡夏· 《奋斗吧，少年！》电视剧片尾曲', 92);
INSERT INTO `list` VALUES ('退让', 29, '曾昱嘉· 《我们不能是朋友》电视剧片头曲', 91);
INSERT INTO `list` VALUES ('まちがいさがし (寻找错误)', 29, '菅田将暉 (すだ まさき)· 《完美世界》日剧片尾曲', 94);
INSERT INTO `list` VALUES ('TV에서 보는 그대 모습은 (在电视里看到的你的样子)', 29, '이다희 (李多喜)· 《请输入搜索词：WWW》韩剧插曲', 93);
INSERT INTO `list` VALUES ('我要飞翔', 29, '炎亚纶· 《请赐我一双翅膀》电视剧片头曲', 95);
INSERT INTO `list` VALUES ('My girl', 29, 'Sonny Rey· 《带着爸爸去留学》电视剧插曲', 96);
INSERT INTO `list` VALUES ('I Just Can\'t Wait to Be King', 29, 'JD McCrary/Shahadi Wright Joseph/John Oliver· 《狮子王》电影插曲', 97);
INSERT INTO `list` VALUES ('归还世界给你', 29, '王铮亮· 《归还世界给你》电视剧片尾曲', 98);
INSERT INTO `list` VALUES ('The Lion Sleeps Tonight (Full Version)', 29, 'Billy Eichner/Seth Rogen· 《狮子王》电影插曲', 99);
INSERT INTO `list` VALUES ('On Fire (Explicit)', 57, 'Yultron/박재범 (朴宰范)', 4);
INSERT INTO `list` VALUES ('Lost Soul', 57, 'Deniz Koyu', 6);
INSERT INTO `list` VALUES ('We Can Get High (RetroVision Remix)', 57, 'Galantis/Yellow Claw', 5);
INSERT INTO `list` VALUES ('Retrograde', 57, 'Hardwell', 7);
INSERT INTO `list` VALUES ('Take Me Back To London', 57, 'Ed Sheeran/Stormzy/Jaykae/Aitch', 3);
INSERT INTO `list` VALUES ('Kylie', 57, 'Mike Williams/Dastic', 8);
INSERT INTO `list` VALUES ('Let Us Love', 57, 'Topic/Vigiland/Christopher', 9);
INSERT INTO `list` VALUES ('Midnight Hour', 57, 'Skrillex/Boys Noize/Ty Dolla $ign', 10);
INSERT INTO `list` VALUES ('Never Be Alone (feat. Aloe Blacc)', 57, 'David Guetta/Aloe Blacc', 11);
INSERT INTO `list` VALUES ('Apart', 57, 'Mako', 12);
INSERT INTO `list` VALUES ('Pica (Cat Dealers Remix)', 57, 'Deorro/Elvis Crespo/Henry Fong', 13);
INSERT INTO `list` VALUES ('Baila Conmigo', 57, 'Yellow Claw/Saweetie/INNA/Jenn Morel', 14);
INSERT INTO `list` VALUES ('Say Goodbye', 57, 'Yultron/Sik-K/식케이 (Sik-K)/pH-1', 15);
INSERT INTO `list` VALUES ('On My Way (Da Tweekaz Remix)', 57, 'Alan Walker/Sabrina Carpenter/Farruko', 16);
INSERT INTO `list` VALUES ('Monster (Robin Schulz Remix)', 57, 'LUM!X/Gabry Ponte', 17);
INSERT INTO `list` VALUES ('Drowning (feat. Sorana)', 57, 'Franklin/Sorana/Digital Farm Animals', 18);
INSERT INTO `list` VALUES ('Body First (董子龙&齐奕同 remix)', 57, '张靓颖', 19);
INSERT INTO `list` VALUES ('Day Or Night', 57, 'Mike Williams', 20);
INSERT INTO `list` VALUES ('Summer Lover feat. Devin & Nile Rogers (CID Remix)', 57, 'Oliver Heldens/Devin/Nile Rodgers', 21);
INSERT INTO `list` VALUES ('Heaven (David Guetta & MORTEN Remix|Extended Version)', 57, 'Avicii', 25);
INSERT INTO `list` VALUES ('More Of Your Love', 57, 'Justin Mylo/Reggio', 22);
INSERT INTO `list` VALUES ('Come Back Down (Original Mix)', 57, 'Mediks', 23);
INSERT INTO `list` VALUES ('Thing For You (David Guetta Remix|Explicit)', 57, 'David Guetta/Martin Solveig', 24);
INSERT INTO `list` VALUES ('Illusion (feat. KARRA)', 57, 'NERVO/Firebeatz/Karra', 26);
INSERT INTO `list` VALUES ('Cool', 57, 'Viva La Panda/Ess Bogale', 27);
INSERT INTO `list` VALUES ('One Thing Right (feat. Kane Brown)', 57, 'Marshmello/Kane Brown', 28);
INSERT INTO `list` VALUES ('Papillon-Postlude of The Rookies 巴比龙 (BOYTOY remix)', 57, '王嘉尔· 《素人特工》电影片尾曲', 29);
INSERT INTO `list` VALUES ('Tell Me Why', 57, 'Alok/Harrison', 30);
INSERT INTO `list` VALUES ('Acordeão', 57, 'Tiësto/Moska', 31);
INSERT INTO `list` VALUES ('Post Malone (feat. RANI) (GATTÜSO Remix)', 57, 'Sam Feldt/Rani', 32);
INSERT INTO `list` VALUES ('Rave (Explicit)', 57, 'Steve Aoki/Showtek/MAKJ/Kris Kiss', 33);
INSERT INTO `list` VALUES ('OMG (MOTi Remix)', 57, 'Gryffin/Carly Rae Jepsen', 34);
INSERT INTO `list` VALUES ('Untamable', 57, 'Wildstylez/Sound Rush/Ruby Prophet', 35);
INSERT INTO `list` VALUES ('I Care (Intro)', 57, 'ILLENIUM', 36);
INSERT INTO `list` VALUES ('Sorry', 57, 'Blaze U', 37);
INSERT INTO `list` VALUES ('Punching in the Dark', 57, 'Hellberg/Aloe Blacc', 38);
INSERT INTO `list` VALUES ('On One (Explicit)', 57, 'Hasho', 39);
INSERT INTO `list` VALUES ('808', 57, '张靓颖· 心电感应808 英文版', 40);
INSERT INTO `list` VALUES ('Need You', 57, 'Faustix', 41);
INSERT INTO `list` VALUES ('방콕 (Bangkok) (Prod. By Francis)', 57, '소유 (昭宥)/Francis (프란시스)', 42);
INSERT INTO `list` VALUES ('Movin\' Too Fast', 57, 'Olly James', 43);
INSERT INTO `list` VALUES ('LONELY NIGHTS (Joel Corry Remix)', 57, 'Benny Benassi/Lil Yachty', 44);
INSERT INTO `list` VALUES ('Long Time', 57, 'Radiology/AXYS/Revealed Recordings', 45);
INSERT INTO `list` VALUES ('All For You', 57, 'RYNX/Kiesza', 46);
INSERT INTO `list` VALUES ('Other Side (feat. Drew Ryn)', 57, 'BlasterJaxx/Drew Ryn', 47);
INSERT INTO `list` VALUES ('This Is The End', 57, 'Gammer/David Spekter', 48);
INSERT INTO `list` VALUES ('GO OFF(Nuthin\' 2 It) (Explicit)', 57, 'Dillon Francis', 49);
INSERT INTO `list` VALUES ('野狼disco', 5, '宝石Gem', 4);
INSERT INTO `list` VALUES ('病态', 5, '薛之谦', 5);
INSERT INTO `list` VALUES ('笑场', 5, '薛之谦', 6);
INSERT INTO `list` VALUES ('你和我都没有错', 5, '都智文', 7);
INSERT INTO `list` VALUES ('胡同少年志', 5, '周深/国道· EDIQ国风音乐连载专辑《国道》', 8);
INSERT INTO `list` VALUES ('一生有你', 5, 'ONER· 《一生有你》电影同名推广曲', 9);
INSERT INTO `list` VALUES ('Promise To You', 5, '汪苏泷· 《我不能恋爱的女朋友》电视剧插曲', 10);
INSERT INTO `list` VALUES ('我和我的祖国', 5, '华语群星· 《我和我的祖国》电影全民版片尾曲', 11);
INSERT INTO `list` VALUES ('野望', 5, '李宇春/Click#15· 《双子杀手》电影主题曲', 12);
INSERT INTO `list` VALUES ('这么久没见', 5, '薛之谦', 13);
INSERT INTO `list` VALUES ('你应该很快乐', 5, '虎二', 15);
INSERT INTO `list` VALUES ('风华', 5, '简弘亦· 《明月照我心》网络剧片头曲', 14);
INSERT INTO `list` VALUES ('还好我们再遇见', 5, '苏诗丁· 《十年三月三十日》电视剧插曲', 16);
INSERT INTO `list` VALUES ('我和我的祖国（青春唱响曲）', 5, '欧豪/周冬雨/朱一龙/刘昊然/陈飞宇', 18);
INSERT INTO `list` VALUES ('不成诗', 5, '双笙', 17);
INSERT INTO `list` VALUES ('Ain\'t Got No Love', 5, '王俊凯', 19);
INSERT INTO `list` VALUES ('何妨年少', 5, '郑云龙· 《厨神小当家》动画片主题曲', 20);
INSERT INTO `list` VALUES ('Banjitino', 5, '卡姆/陆政廷Lil Jet', 21);
INSERT INTO `list` VALUES ('彩虹弧线', 5, '许魏洲', 22);
INSERT INTO `list` VALUES ('我的中国心', 5, '肖战', 23);
INSERT INTO `list` VALUES ('海', 5, '王子异', 24);
INSERT INTO `list` VALUES ('暑假', 5, '好妹妹', 25);
INSERT INTO `list` VALUES ('远在咫尺的爱', 5, '房东的猫· 《彩虹的重力》电视剧主题曲', 26);
INSERT INTO `list` VALUES ('幸福第一站', 5, '庄心妍', 27);
INSERT INTO `list` VALUES ('西子吟', 5, '胡66', 28);
INSERT INTO `list` VALUES ('失态 (Misbehave)', 5, '余佳运', 29);
INSERT INTO `list` VALUES ('碰碰', 5, '周奇', 30);
INSERT INTO `list` VALUES ('如斟', 5, 'Mukyo木西', 31);
INSERT INTO `list` VALUES ('星途', 5, '张靓颖· EXEED星途LX专属主题曲', 32);
INSERT INTO `list` VALUES ('Do You Want More', 5, '黄旭', 33);
INSERT INTO `list` VALUES ('原来我', 5, '刘惜君· 《十年三月三十日》电视剧片尾曲', 34);
INSERT INTO `list` VALUES ('没有说完的故事', 5, '周深· 《美食大冒险之英雄烩》动画电影片尾曲', 35);
INSERT INTO `list` VALUES ('我和我的祖国 (全民合唱版)', 5, '廖昌永/张艺兴/火箭少女101段奥娟/张远/连淮伟/焦迈奇/全民K歌用户', 36);
INSERT INTO `list` VALUES ('我不好', 5, '张艺兴', 37);
INSERT INTO `list` VALUES ('常客', 5, '秦昊· 《常客》秦昊摄影集主题曲', 38);
INSERT INTO `list` VALUES ('相遇的可能', 5, '马伊琍· 《在远方》电视剧插曲', 39);
INSERT INTO `list` VALUES ('\"她\"', 5, '杨和苏KeyNG', 42);
INSERT INTO `list` VALUES ('亲爱的你 去了何方', 5, '陈硕子', 40);
INSERT INTO `list` VALUES ('卸任', 5, '谢宇伦', 41);
INSERT INTO `list` VALUES ('念殊途', 5, '河图/阿杰729· 伶伦人物曲', 43);
INSERT INTO `list` VALUES ('南方北方', 5, '康树龙', 44);
INSERT INTO `list` VALUES ('时间的脉络', 5, '王铮亮· 《十年三月三十日》电视剧主题曲', 45);
INSERT INTO `list` VALUES ('红色高跟鞋', 5, '隔壁老樊', 46);
INSERT INTO `list` VALUES ('自省', 5, '何玄· 《十年三月三十日》电视剧插曲', 47);
INSERT INTO `list` VALUES ('初见雪', 5, '方逸伦/凌美仕· 《明月照我心》网络剧片尾曲', 48);
INSERT INTO `list` VALUES ('复乐园', 5, '二珂', 49);
INSERT INTO `list` VALUES ('徐竹隐', 5, '贰婶/歪歪· 八音掌竹-严辞人物曲', 50);
INSERT INTO `list` VALUES ('循', 5, '双笙', 51);
INSERT INTO `list` VALUES ('就当从没遇见你', 5, '小沈阳', 52);
INSERT INTO `list` VALUES ('祖国', 5, '南征北战NZBZ· 共青团中央宣传部联合出品', 53);
INSERT INTO `list` VALUES ('太多', 5, '简弘亦', 55);
INSERT INTO `list` VALUES ('木梓姑娘', 5, '虎二', 54);
INSERT INTO `list` VALUES ('玉剑掀澜', 5, '银临/云の泣/清弄· 英雄联盟2019玉剑传说系列皮肤同人主题曲', 56);
INSERT INTO `list` VALUES ('我爱祖国的蓝天', 5, '毛阿敏· 《中国机长》电影主题曲', 57);
INSERT INTO `list` VALUES ('远方', 5, '金志文· 《在远方》电视剧主题曲', 58);
INSERT INTO `list` VALUES ('青春狂想曲', 5, '陈学冬', 59);
INSERT INTO `list` VALUES ('问少年', 5, '肖战· 《诛仙I》电影放肆版主题曲', 60);
INSERT INTO `list` VALUES ('净土谣', 5, '小魂/谷江山· 八音掌土-苏与白人物曲', 61);
INSERT INTO `list` VALUES ('今后我与自己流浪', 5, '张碧晨· 《哪吒之魔童降世》电影片尾曲', 62);
INSERT INTO `list` VALUES ('王昭君', 5, '陈雪凝· 《王者荣耀》英雄主打歌', 63);
INSERT INTO `list` VALUES ('进退无路', 5, '南征北战NZBZ', 64);
INSERT INTO `list` VALUES ('Ethereal', 5, '痛仰乐队', 65);
INSERT INTO `list` VALUES ('噩梦', 5, 'Tizzy T', 66);
INSERT INTO `list` VALUES ('Fall', 5, '易烊千玺', 67);
INSERT INTO `list` VALUES ('少年', 5, '郑棋元· 《光荣时代》电视剧插曲', 68);
INSERT INTO `list` VALUES ('Shyuwa shyuwa', 5, '洛天依', 69);
INSERT INTO `list` VALUES ('彩虹冰淇淋', 5, '周艺轩· 《我不能恋爱的女朋友》恋爱暖身曲', 70);
INSERT INTO `list` VALUES ('小欢喜', 5, '刘瑞琦· 《小欢喜》电视剧同名主题曲', 71);
INSERT INTO `list` VALUES ('梦', 5, '蔡徐坤', 72);
INSERT INTO `list` VALUES ('与未来对话', 5, '范丞丞', 73);
INSERT INTO `list` VALUES ('第一次告白', 5, 'TFBOYS', 74);
INSERT INTO `list` VALUES ('大力水手', 5, '黄旭', 75);
INSERT INTO `list` VALUES ('流光卷', 5, '河图/汐音社', 76);
INSERT INTO `list` VALUES ('寻光', 5, '戴景耀· 《呼吸》电影中文推广曲', 78);
INSERT INTO `list` VALUES ('孤岛', 5, '胡夏· 《空降利刃》电视剧插曲', 77);
INSERT INTO `list` VALUES ('容身之所', 5, '双笙· 《罗小黑战记》电影印象曲', 79);
INSERT INTO `list` VALUES ('情意结', 5, '周深· 《诛仙I》电影片尾曲', 80);
INSERT INTO `list` VALUES ('翱翔天地', 5, '胡夏· 《中国机长》电影插曲', 81);
INSERT INTO `list` VALUES ('听我说说', 5, '赵天宇· 《我的莫格利男孩》电视剧插曲', 83);
INSERT INTO `list` VALUES ('碌碌无为', 5, '刘彬濠', 84);
INSERT INTO `list` VALUES ('避难所/Sanctuary', 5, '周深· 《我在未来等你》电视剧暗恋主题曲', 82);
INSERT INTO `list` VALUES ('爱我行不行', 5, '徐良/二珂· 《我不能恋爱的女朋友》插曲', 85);
INSERT INTO `list` VALUES ('陷落美好', 5, '易烊千玺', 86);
INSERT INTO `list` VALUES ('各自安好', 5, '高嘉朗', 87);
INSERT INTO `list` VALUES ('来日没有那么长', 5, '虎二', 89);
INSERT INTO `list` VALUES ('良人遮', 5, '刘珂矣', 88);
INSERT INTO `list` VALUES ('栽种梦想', 5, 'ONER', 90);
INSERT INTO `list` VALUES ('如果当时', 5, '胡夏· 《上海堡垒》电影推广曲', 91);
INSERT INTO `list` VALUES ('巅峰之上', 5, '毛不易· 《全职高手》电视剧主题曲', 92);
INSERT INTO `list` VALUES ('我和我的祖国 (童声版)', 5, '邓文怡/邓力玮', 93);
INSERT INTO `list` VALUES ('蒙着眼', 5, '蔡徐坤', 94);
INSERT INTO `list` VALUES ('阴天', 5, '痛仰乐队', 95);
INSERT INTO `list` VALUES ('好吗, 好啦, 好吧', 5, '刘柏辛Lexie', 96);
INSERT INTO `list` VALUES ('讲真的', 5, '摩登兄弟', 97);
INSERT INTO `list` VALUES ('一个人旅行', 5, '李凡一', 98);
INSERT INTO `list` VALUES ('告白前一秒', 5, '永彬Ryan.B', 99);
INSERT INTO `list` VALUES ('Drown', 3, 'Martin Garrix/Clinton Kane', 3);
INSERT INTO `list` VALUES ('Stupid Love', 3, 'Lady Gaga', 4);
INSERT INTO `list` VALUES ('I Found You', 3, 'Cash Cash/Andy Grammer', 6);
INSERT INTO `list` VALUES ('Loyal Brave True (From \"Mulan\")', 3, 'Christina Aguilera', 5);
INSERT INTO `list` VALUES ('Roar', 3, 'Katy Perry', 7);
INSERT INTO `list` VALUES ('Only The Young (Featured in Miss Americana)', 3, 'Taylor Swift', 8);
INSERT INTO `list` VALUES ('I Love Me (Explicit)', 3, 'Demi Lovato', 9);
INSERT INTO `list` VALUES ('Drugs & The Internet (Explicit)', 3, 'Lauv', 10);
INSERT INTO `list` VALUES ('Oh My God', 3, 'Alec Benjamin', 11);
INSERT INTO `list` VALUES ('The Book of You & I', 3, 'Alec Benjamin', 12);
INSERT INTO `list` VALUES ('What Goes Up', 3, 'Lenka', 13);
INSERT INTO `list` VALUES ('The Other Side', 3, 'SZA/Justin Timberlake', 14);
INSERT INTO `list` VALUES ('Bammer (Explicit)', 3, 'Wiz Khalifa/Mustard', 15);
INSERT INTO `list` VALUES ('Feel Me', 3, 'Selena Gomez', 16);
INSERT INTO `list` VALUES ('Yummy (Country Remix)', 3, 'Justin Bieber/Florida Georgia Line', 17);
INSERT INTO `list` VALUES ('The Man (Live From Paris)', 3, 'Taylor Swift', 18);
INSERT INTO `list` VALUES ('AAA', 3, 'NYK/Shelhiel', 19);
INSERT INTO `list` VALUES ('No Time To Die', 3, 'Billie Eilish', 20);
INSERT INTO `list` VALUES ('Mistakes (Explicit)', 3, 'Jonas Blue/Paloma Faith', 21);
INSERT INTO `list` VALUES ('Shake It Off', 3, 'Taylor Swift', 22);
INSERT INTO `list` VALUES ('Let\'s Go', 3, 'Tobu', 23);
INSERT INTO `list` VALUES ('This is Us', 3, 'Jimmie Allen/Noah Cyrus', 24);
INSERT INTO `list` VALUES ('i\'m so tired...', 3, 'Lauv/Troye Sivan', 25);
INSERT INTO `list` VALUES ('I Don’t Wanna Live Forever (Fifty Shades Darker) (From \"Fifty Shades Darker (Original Motion Picture Soundtrack)\")', 3, 'ZAYN/Taylor Swift', 26);
INSERT INTO `list` VALUES ('To Die For', 3, 'Sam Smith', 27);
INSERT INTO `list` VALUES ('Sorry', 3, 'Justin Bieber', 28);
INSERT INTO `list` VALUES ('fuck, i\'m lonely (Explicit)', 3, 'Lauv/Anne-Marie', 29);
INSERT INTO `list` VALUES ('Poker Face', 3, 'Lady Gaga', 30);
INSERT INTO `list` VALUES ('Alone, Pt. II', 3, 'Alan Walker/Ava Max', 31);
INSERT INTO `list` VALUES ('Lonely Eyes', 3, 'Lauv', 32);
INSERT INTO `list` VALUES ('Alone, Pt. II (Live at Château de Fontainebleau)', 3, 'Alan Walker/Ava Max', 33);
INSERT INTO `list` VALUES ('Modern Loneliness (Explicit)', 3, 'Lauv', 34);
INSERT INTO `list` VALUES ('Young & Alive', 3, 'Bazzi', 35);
INSERT INTO `list` VALUES ('As Long As You Love Me (Acoustic Version)', 3, 'Justin Bieber', 36);
INSERT INTO `list` VALUES ('Into the Unknown', 3, 'AURORA', 37);
INSERT INTO `list` VALUES ('Dancing Next To Me', 3, 'Greyson Chance', 38);
INSERT INTO `list` VALUES ('CHIME OF THE  DAWN BELLS（黎明的编钟声）', 3, 'Noémie Maljean/Jean-Francois Maljean', 39);
INSERT INTO `list` VALUES ('Baby Pluto (Explicit)', 3, 'Lil Uzi Vert', 40);
INSERT INTO `list` VALUES ('Feelings', 3, 'Lauv', 41);
INSERT INTO `list` VALUES ('Priceless', 3, 'Beatrich', 42);
INSERT INTO `list` VALUES ('Not Alone', 3, 'Skytech/TWISTERZ', 43);
INSERT INTO `list` VALUES ('Canada', 3, 'Lauv/Alessia Cara', 45);
INSERT INTO `list` VALUES ('Honest', 3, 'Kristian Kostov', 44);
INSERT INTO `list` VALUES ('Any Song(Tik Tok Dance Challenge Version)[Originally Performed by ZICO]', 3, 'Elliot Van Coup', 46);
INSERT INTO `list` VALUES ('Intentions', 3, 'Justin Bieber/Quavo', 47);
INSERT INTO `list` VALUES ('Despacito', 3, 'Luis Fonsi/Daddy Yankee', 48);
INSERT INTO `list` VALUES ('Physical', 3, 'Dua Lipa', 49);
INSERT INTO `list` VALUES ('After Hours', 3, 'The Weeknd', 50);
INSERT INTO `list` VALUES ('Always (Alan Walker Remix)', 3, 'Gavin James/Alan Walker', 51);
INSERT INTO `list` VALUES ('Girls Like You', 3, 'Boyce Avenue', 52);
INSERT INTO `list` VALUES ('Sims (Explicit)', 3, 'Lauv', 53);
INSERT INTO `list` VALUES ('I Luv U (R3HAB VIP Remix)', 3, 'Sofia Carson/R3HAB', 54);
INSERT INTO `list` VALUES ('In the End', 3, 'Linkin Park', 55);
INSERT INTO `list` VALUES ('My Sunset (Original Mix)', 3, 'Feint', 56);
INSERT INTO `list` VALUES ('Billy', 3, 'Lauv', 57);
INSERT INTO `list` VALUES ('fear', 3, 'gnash', 58);
INSERT INTO `list` VALUES ('SUGAR (feat. Dua Lipa) (Remix)', 3, 'Brockhampton/Dua Lipa', 59);
INSERT INTO `list` VALUES ('Believed', 3, 'Lauv', 60);
INSERT INTO `list` VALUES ('Mean', 3, 'Taylor Swift', 61);
INSERT INTO `list` VALUES ('Love Yourself', 3, 'Justin Bieber', 63);
INSERT INTO `list` VALUES ('On My Side', 3, 'Lenka', 62);
INSERT INTO `list` VALUES ('El Mejor Guerrero (De \"Mulán\")', 3, 'Christina Aguilera', 64);
INSERT INTO `list` VALUES ('To Die For (Ólafur Arnalds Remix)', 3, 'Sam Smith', 65);
INSERT INTO `list` VALUES ('Mean It', 3, 'Lauv/LANY', 66);
INSERT INTO `list` VALUES ('For Now', 3, 'Lauv', 67);
INSERT INTO `list` VALUES ('Gaslighter', 3, 'Dixie Chicks', 68);
INSERT INTO `list` VALUES ('Flashback', 3, 'Beatrich', 69);
INSERT INTO `list` VALUES ('Tell My Mama', 3, 'Lauv', 70);
INSERT INTO `list` VALUES ('River', 3, 'Bishop Briggs', 71);
INSERT INTO `list` VALUES ('We Will Rock You', 3, 'Nickelback', 72);
INSERT INTO `list` VALUES ('Dance Monkey (Original remix)', 3, 'Tones and I/Dj Afonso De Vic', 73);
INSERT INTO `list` VALUES ('All Around Me', 3, 'Justin Bieber', 74);
INSERT INTO `list` VALUES ('Rare (Alexander 23 Edit)', 3, 'Selena Gomez/Alexander 23', 75);
INSERT INTO `list` VALUES ('Señorita', 3, 'Boyce Avenue', 78);
INSERT INTO `list` VALUES ('Yummy', 3, 'Justin Bieber', 76);
INSERT INTO `list` VALUES ('Please Don\'t Go', 3, 'BEAUZ/BSY/JSY/CAPPA', 77);
INSERT INTO `list` VALUES ('Right Here Waiting', 3, 'Richard Marx', 79);
INSERT INTO `list` VALUES ('Call Me Maybe', 3, 'Carly Rae Jepsen', 80);
INSERT INTO `list` VALUES ('Changes', 3, 'Lauv', 81);
INSERT INTO `list` VALUES ('The Storm', 3, 'TheFatRat/Maisy Kay', 82);
INSERT INTO `list` VALUES ('Numb', 3, 'Linkin Park', 83);
INSERT INTO `list` VALUES ('Counting Stars', 3, 'OneRepublic', 84);
INSERT INTO `list` VALUES ('7 rings', 3, 'Ariana Grande', 85);
INSERT INTO `list` VALUES ('Life Is Good (Explicit)', 3, 'Future/Drake', 86);
INSERT INTO `list` VALUES ('Rare (Live From The Village Studio)', 3, 'Selena Gomez', 87);
INSERT INTO `list` VALUES ('Forever Yours (Avicii Tribute)', 3, 'Kygo/Avicii/Sandro Cavazza', 89);
INSERT INTO `list` VALUES ('Stay With You', 3, 'Gavrio/Ted Giovanni R. Bacalso Jr.', 88);
INSERT INTO `list` VALUES ('El Tejano (Explicit)', 3, 'Lauv/Sofia Reyes', 91);
INSERT INTO `list` VALUES ('Come Around Me', 3, 'Justin Bieber', 90);
INSERT INTO `list` VALUES ('Julia', 3, 'Lauv', 92);
INSERT INTO `list` VALUES ('Stand By Me', 3, 'John Newman', 93);
INSERT INTO `list` VALUES ('Old Me (Explicit)', 3, '5 Seconds Of Summer', 95);
INSERT INTO `list` VALUES ('How To Love(feat. GRAY)', 3, 'ALLY/GRAY (그레이)', 94);
INSERT INTO `list` VALUES ('Apologize (Album Version)', 3, 'OneRepublic', 96);
INSERT INTO `list` VALUES ('Rojo', 3, 'J Balvin', 97);
INSERT INTO `list` VALUES ('Friendships (2020 Dance Remix)', 3, 'Blane Tide', 98);
INSERT INTO `list` VALUES ('Birthday', 3, 'Anne-Marie', 99);
INSERT INTO `list` VALUES ('你要相信这不是最后一天', 27, '华晨宇', 4);
INSERT INTO `list` VALUES ('End of Time', 27, 'K-391/Alan Walker/Ahrix', 5);
INSERT INTO `list` VALUES ('冬日', 27, '鞠婧祎', 6);
INSERT INTO `list` VALUES ('Will You Marry Me', 27, '一口甜', 7);
INSERT INTO `list` VALUES ('给女孩（单曲）', 27, '李宇春', 8);
INSERT INTO `list` VALUES ('终于', 27, '双笙· 《两世欢》电视剧片头主题曲', 9);
INSERT INTO `list` VALUES ('朋友请听好', 27, '何炅/谢娜/易烊千玺· 《朋友请听好》芒果TV自制综艺同名主题曲', 10);
INSERT INTO `list` VALUES ('眠冬', 27, '满舒克/黄明昊', 11);
INSERT INTO `list` VALUES ('时光与你都很甜', 27, '吕小雨/孙泽源· 《时光与你都很甜》网剧同名主题曲', 12);
INSERT INTO `list` VALUES ('知晚', 27, '叶炫清· 《两世欢》电视剧插曲', 15);
INSERT INTO `list` VALUES ('海月之端', 27, '双笙', 13);
INSERT INTO `list` VALUES ('每个人都是孤独的', 27, '苏晗', 14);
INSERT INTO `list` VALUES ('身边', 27, '孙泽源· 《时光与你都很甜》网剧片尾曲', 16);
INSERT INTO `list` VALUES ('因为我们在一起', 27, '王一博', 17);
INSERT INTO `list` VALUES ('FIESTA', 27, 'IZ*ONE (아이즈원)', 18);
INSERT INTO `list` VALUES ('想你', 27, '艾辰', 19);
INSERT INTO `list` VALUES ('王源：快跟着我进入文物的时空漫游吧！', 27, '王源', 20);
INSERT INTO `list` VALUES ('孤单的人', 27, '海来阿木', 22);
INSERT INTO `list` VALUES ('青春不打烊', 27, '郭静· 《时光与你都很甜》网剧片头曲', 21);
INSERT INTO `list` VALUES ('영웅 (英雄; Kick It)', 27, 'NCT 127 (엔씨티 127)', 23);
INSERT INTO `list` VALUES ('不完美的完美', 27, '金玟岐· 《完美关系》电视剧宣传主题曲', 24);
INSERT INTO `list` VALUES ('Drown', 27, 'Martin Garrix/Clinton Kane', 25);
INSERT INTO `list` VALUES ('自己', 27, '刘亦菲· 电影《花木兰》中文主题曲', 26);
INSERT INTO `list` VALUES ('Stupid Love', 27, 'Lady Gaga', 27);
INSERT INTO `list` VALUES ('也许', 27, '于文文· 《谁都渴望遇见你》网台剧片尾曲', 28);
INSERT INTO `list` VALUES ('Never Worn White', 27, 'Katy Perry', 29);
INSERT INTO `list` VALUES ('平安回来', 27, '景甜/谭松韵/白宇', 30);
INSERT INTO `list` VALUES ('下凡', 27, '祝眠', 31);
INSERT INTO `list` VALUES ('渴望遇见', 27, '周深· 《谁都渴望遇见你》网台剧主题曲', 32);
INSERT INTO `list` VALUES ('Loyal Brave True (From \"Mulan\")', 27, 'Christina Aguilera', 33);
INSERT INTO `list` VALUES ('No Time To Die', 27, 'Billie Eilish', 34);
INSERT INTO `list` VALUES ('橱窗', 27, '冯希瑶· 《安家》电视剧片尾曲', 35);
INSERT INTO `list` VALUES ('Who (feat. BTS)', 27, 'Lauv/BTS (防弹少年团)', 36);
INSERT INTO `list` VALUES ('逃离', 27, '王金金· 《谁都渴望遇见你》网台剧插曲', 37);
INSERT INTO `list` VALUES ('Yummy (Country Remix)', 27, 'Justin Bieber/Florida Georgia Line', 38);
INSERT INTO `list` VALUES ('二十岁的遗言', 27, '陈思键', 39);
INSERT INTO `list` VALUES ('Oh My God', 27, 'Alec Benjamin', 40);
INSERT INTO `list` VALUES ('有你在身边', 27, '韩庚/杨颖/王一博/郑爽', 41);
INSERT INTO `list` VALUES ('走散', 27, '都智文· 《少主且慢行》电视剧插曲', 42);
INSERT INTO `list` VALUES ('꿈 (Boom) (梦)', 27, 'NCT 127 (엔씨티 127)', 43);
INSERT INTO `list` VALUES ('Feel Me', 27, 'Selena Gomez', 44);
INSERT INTO `list` VALUES ('不如先庆祝能在一起', 27, '萧亚轩', 45);
INSERT INTO `list` VALUES ('어떤 말도 (No Words)', 27, 'Crush (크러쉬)· 《梨泰院Class》韩剧插曲', 46);
INSERT INTO `list` VALUES ('I Found You', 27, 'Cash Cash/Andy Grammer', 47);
INSERT INTO `list` VALUES ('The Man (Live From Paris)', 27, 'Taylor Swift', 48);
INSERT INTO `list` VALUES ('Elevator (127F)', 27, 'NCT 127 (엔씨티 127)', 49);
INSERT INTO `list` VALUES ('雨水', 27, '音阙诗听/李佳思', 50);
INSERT INTO `list` VALUES ('保重', 27, '王俊凯/谢霆锋/萧敬腾', 51);
INSERT INTO `list` VALUES ('Sit Down!', 27, 'NCT 127 (엔씨티 127)', 52);
INSERT INTO `list` VALUES ('TING TING TING with Oliver Heldens', 27, 'ITZY (있지)/Oliver Heldens', 53);
INSERT INTO `list` VALUES ('NOBODY LIKE YOU', 27, 'ITZY (있지)', 54);
INSERT INTO `list` VALUES ('晚吟', 27, '李俊毅· 《两世欢》电视剧插曲', 55);
INSERT INTO `list` VALUES ('그때 그 아인 (Someday, The Boy)', 27, '金弼 (김필)· 《梨泰院Class》韩剧插曲', 56);
INSERT INTO `list` VALUES ('自从遇见你', 27, '虞书欣· 《少主且慢行》电视剧插曲', 57);
INSERT INTO `list` VALUES ('메아리 (Love Me Now) (回响)', 27, 'NCT 127 (엔씨티 127)', 58);
INSERT INTO `list` VALUES ('백야 (White Night) (白夜)', 27, 'NCT 127 (엔씨티 127)', 62);
INSERT INTO `list` VALUES ('时光成语花落地', 27, '宁桓宇· 《完美关系》电视剧片尾曲', 59);
INSERT INTO `list` VALUES ('THAT’S A NO NO', 27, 'ITZY (있지)', 60);
INSERT INTO `list` VALUES ('우산 (Love Song) (雨伞)', 27, 'NCT 127 (엔씨티 127)', 61);
INSERT INTO `list` VALUES ('낮잠 (Pandora\'s Box) (午睡)', 27, 'NCT 127 (엔씨티 127)', 63);
INSERT INTO `list` VALUES ('YOU MAKE ME', 27, 'ITZY (있지)', 64);
INSERT INTO `list` VALUES ('Not Alone', 27, 'NCT 127 (엔씨티 127)', 65);
INSERT INTO `list` VALUES ('To Die For', 27, 'Sam Smith', 66);
INSERT INTO `list` VALUES ('Day Dream (白日夢)', 27, 'NCT 127 (엔씨티 127)', 67);
INSERT INTO `list` VALUES ('我的回答', 27, '王啸坤· 《谁都渴望遇见你》网台剧人物主题曲', 68);
INSERT INTO `list` VALUES ('我不是她', 27, 'HANA菊梓乔· 《法证先锋IV》电视剧片尾曲', 69);
INSERT INTO `list` VALUES ('뿔 (MAD DOG) (角)', 27, 'NCT 127 (엔씨티 127)', 70);
INSERT INTO `list` VALUES ('一心一念', 27, '欧阳娜娜· 《北灵少年志之大主宰》电视剧片尾曲', 71);
INSERT INTO `list` VALUES ('一世倾心', 27, '双笙· 《热血同行》电视剧插曲', 72);
INSERT INTO `list` VALUES ('微光/Gleam', 27, '郑云龙/蔡程昱', 73);
INSERT INTO `list` VALUES ('不爱而别', 27, '火箭少女101紫宁· 《少主且慢行》电视剧插曲', 74);
INSERT INTO `list` VALUES ('Tell me', 27, 'milet (ミレイ)· 《Fate/Grand Order -绝对魔兽战线巴比伦尼亚-》TV动画片尾曲', 75);
INSERT INTO `list` VALUES ('The Other Side', 27, 'SZA/Justin Timberlake', 76);
INSERT INTO `list` VALUES ('Say', 27, '尹美莱 (윤미래)· 《梨泰院Class》韩剧插曲', 77);
INSERT INTO `list` VALUES ('少年战', 27, '汪苏泷· 《热血同行》电视剧片尾曲、主题曲', 78);
INSERT INTO `list` VALUES ('AYAYAYA', 27, 'IZ*ONE (아이즈원)', 79);
INSERT INTO `list` VALUES ('RED MOON', 27, 'KARD (카드)', 80);
INSERT INTO `list` VALUES ('爱的桥梁 (粤语版)〝我知道〞', 27, '刘德华', 81);
INSERT INTO `list` VALUES ('我不是病毒', 27, '音阙诗听/昆玉', 82);
INSERT INTO `list` VALUES ('24HRS', 27, 'ITZY (있지)', 83);
INSERT INTO `list` VALUES ('AAA', 27, 'NYK/Shelhiel', 84);
INSERT INTO `list` VALUES ('Dreams Come True', 27, 'NCT 127 (엔씨티 127)', 85);
INSERT INTO `list` VALUES ('This is Us', 27, 'Jimmie Allen/Noah Cyrus', 86);
INSERT INTO `list` VALUES ('달이 태양을 가릴 때 (Eclipse)', 27, '玟星 (문별)', 87);
INSERT INTO `list` VALUES ('Always (Alan Walker Remix)', 27, 'Gavin James/Alan Walker', 90);
INSERT INTO `list` VALUES ('Alone, Pt. II (Live at Château de Fontainebleau)', 27, 'Alan Walker/Ava Max', 91);
INSERT INTO `list` VALUES ('I’m Falling in Love', 27, '郭静/宁桓宇· 《少主且慢行》电视剧插曲', 88);
INSERT INTO `list` VALUES ('时间里的小偷', 27, '庄心妍', 89);
INSERT INTO `list` VALUES ('天下局', 27, '高天鹤', 92);
INSERT INTO `list` VALUES ('Interlude: Neo Zone', 27, 'NCT 127 (엔씨티 127)', 93);
INSERT INTO `list` VALUES ('I DON’T WANNA DANCE', 27, 'ITZY (있지)', 94);
INSERT INTO `list` VALUES ('この歌に誓おう (以此歌为誓)', 27, '吉田亚纪子 (KOKIA)· 《魔道祖师》日文版广播剧主题曲|《何以歌》日语版', 96);
INSERT INTO `list` VALUES ('What Goes Up', 27, 'Lenka', 97);
INSERT INTO `list` VALUES ('一样美丽 (同心版)', 27, '周兴哲/黄妍/林奕匡/E.Viewz/Sezairi/陈柏宇/Benjamin Kheng/Ben&Ben/郑心慈/Narelle/陈明憙Jocelyn/NYK/Hà Lê/Wafa Bahiyya Haneesa/Fatin', 95);
INSERT INTO `list` VALUES ('솔직히 지친다 (Everybody Has)', 27, '金请夏 (김청하)', 99);
INSERT INTO `list` VALUES ('Come Around Me', 27, 'Justin Bieber', 98);
INSERT INTO `list` VALUES ('ありがとうはこっちの言葉 (谢谢是我要说的话)', 17, '森山直太朗 (もりやま なおたろう)· 《索玛丽与森林之神》TV动画片头曲', 6);
INSERT INTO `list` VALUES ('無限大 (INFINITY)', 17, 'JO1 (ジェイオーワン)', 4);
INSERT INTO `list` VALUES ('パプリカ (红辣椒)', 17, '米津玄師 (よねづ けんし)', 5);
INSERT INTO `list` VALUES ('Tell me', 17, 'milet (ミレイ)· 《Fate/Grand Order -绝对魔兽战线巴比伦尼亚-》TV动画片尾曲', 7);
INSERT INTO `list` VALUES ('ミスターフィクサー (Mr. Fixer)', 17, 'Sou· 《异度侵入 ID:INVADED》TV动画片头曲', 8);
INSERT INTO `list` VALUES ('Running', 17, 'JO1 (ジェイオーワン)', 9);
INSERT INTO `list` VALUES ('永遠の不在証明 (永远的不在场证明)', 17, '東京事変· 《名侦探柯南：绯色的子弹》剧场版主题曲', 10);
INSERT INTO `list` VALUES ('Sacrifice', 17, 'majiko (まじ娘)', 11);
INSERT INTO `list` VALUES ('アリシア (Alicia)', 17, 'ClariS (クラリス)· 《魔法纪录 魔法少女小圆外传》TV动画片尾曲', 12);
INSERT INTO `list` VALUES ('La Pa Pa Pam', 17, 'JO1 (ジェイオーワン)', 13);
INSERT INTO `list` VALUES ('One Summer\'s Day (from \'Spirited Away\')', 17, '久石让 (ひさいし じょう)/新日本フィルハーモニー交響楽団 (New Japan Philharmonic Orchestra)', 14);
INSERT INTO `list` VALUES ('Tiny Light', 17, '鬼頭明里 (きとう あかり)· 《地缚少年花子君》TV动画片尾曲', 15);
INSERT INTO `list` VALUES ('Prover', 17, 'milet (ミレイ)· 《Fate/Grand Order -绝对魔兽战线巴比伦尼亚-》TV动画片尾曲', 16);
INSERT INTO `list` VALUES ('Good Night', 17, '佐々木李子 (ささき りこ)· 《因为太怕痛就全点防御力了》TV动画插曲', 17);
INSERT INTO `list` VALUES ('モラトリアム (Moratorium)', 17, 'Omoinotake (オモイノタケ)· 《鸣鸟不飞:乌云密布》动画电影主题曲', 18);
INSERT INTO `list` VALUES ('光れ', 17, '鹿乃 (かの)', 19);
INSERT INTO `list` VALUES ('I LOVE...', 17, 'Official髭男dism (Official Hige Dandism)· 《将恋爱进行到底》日剧主题曲', 20);
INSERT INTO `list` VALUES ('エスカルゴ (蜗牛)', 17, 'majiko (まじ娘)', 21);
INSERT INTO `list` VALUES ('Summer', 17, '久石让 (ひさいし じょう)/新日本フィルハーモニー交響楽団 (New Japan Philharmonic Orchestra)', 22);
INSERT INTO `list` VALUES ('unlasting', 17, 'LiSA (織部里沙)· 《刀剑神域 Ⅲ》TV动画片尾曲', 23);
INSERT INTO `list` VALUES ('yours', 17, '鹿乃 (かの)', 24);
INSERT INTO `list` VALUES ('No.7', 17, '生田鷹司 (いくた ようじ)/大石昌良 (オーイシマサヨシ)/ZiNG· 《地缚少年花子君》TV动画片头曲', 25);
INSERT INTO `list` VALUES ('聴いて', 17, '鹿乃 (かの)', 26);
INSERT INTO `list` VALUES ('KILIG', 17, '鹿乃 (かの)', 27);
INSERT INTO `list` VALUES ('漫ろ雨', 17, '鹿乃 (かの)', 28);
INSERT INTO `list` VALUES ('はじまりの詩', 17, '初音未来 (初音ミク)/東北きりたん/神様うさぎ', 29);
INSERT INTO `list` VALUES ('Kiki\'s Delivery Service (From \'Kiki\'s Delivery Service\')', 17, '久石让 (ひさいし じょう)/London Symphony Orchestra', 30);
INSERT INTO `list` VALUES ('have a nice day', 17, '浅葱喵asagiinyo', 31);
INSERT INTO `list` VALUES ('罰と罰 (罚与罚)', 17, '鹿乃 (かの)', 32);
INSERT INTO `list` VALUES ('CHAIN', 17, 'ASCA (アスカ)· 《达尔文游戏》TV动画片头曲', 33);
INSERT INTO `list` VALUES ('Innocent (映画「天空の城ラピュタ」より)', 17, '久石让 (ひさいし じょう)', 34);
INSERT INTO `list` VALUES ('エンディングノート (Ending Note)', 17, '鹿乃 (かの)', 35);
INSERT INTO `list` VALUES ('さよならの今日に (在告別的今天)', 17, '爱缪 (あいみょん)· 《news zero》新闻节目主题曲', 38);
INSERT INTO `list` VALUES ('No.7 (オーイシマサヨシver.)', 17, '大石昌良 (オーイシマサヨシ)', 36);
INSERT INTO `list` VALUES ('Merry-Go-Round', 17, '久石让 (ひさいし じょう)', 37);
INSERT INTO `list` VALUES ('In The Flames', 17, 'Chanmina (ちゃんみな)', 39);
INSERT INTO `list` VALUES ('YOUNG (JO1 ver.)', 17, 'JO1 (ジェイオーワン)', 41);
INSERT INTO `list` VALUES ('おかえり', 17, '鹿乃 (かの)', 40);
INSERT INTO `list` VALUES ('GrandMaster (JO1 ver.)', 17, 'JO1 (ジェイオーワン)', 42);
INSERT INTO `list` VALUES ('ツカメ～It\'s Coming～ (JO1 ver.)', 17, 'JO1 (ジェイオーワン)', 43);
INSERT INTO `list` VALUES ('Running', 17, 'JO1 (ジェイオーワン)', 44);
INSERT INTO `list` VALUES ('ランデヴー (Rendezvous)', 17, '三月的幻想 (三月のパンタシア)', 45);
INSERT INTO `list` VALUES ('モラトリアム (Moratorium)', 17, 'Omoinotake (オモイノタケ)· 《鸣鸟不飞:乌云密布》动画电影主题曲', 46);
INSERT INTO `list` VALUES ('グリム (格林)', 17, 'majiko (まじ娘)', 47);
INSERT INTO `list` VALUES ('REAL×EYEZ', 17, 'J (小野瀬潤)/T.M.Revolution (ティー・エム・レボリューション)· 《假面骑士ZERO-ONE》特摄剧主题曲', 48);
INSERT INTO `list` VALUES ('群青', 17, '神山羊 (かみやま よう)· 《猎龙飞船》TV动画片头曲', 50);
INSERT INTO `list` VALUES ('フレンズ (Friends)', 17, 'wacci (ワッチ)· 《家有圆圆?!我家的圆圆你知道吗?》TV动画片头曲', 49);
INSERT INTO `list` VALUES ('Tiny Light (TV Size)', 17, '鬼頭明里 (きとう あかり)· 《地缚少年花子君》TV动画片尾曲', 51);
INSERT INTO `list` VALUES ('23', 17, 'Rude-α (ルードアルファ)', 52);
INSERT INTO `list` VALUES ('スタンドバイミー (Stand By Me)', 17, '神山羊 (かみやま よう)', 53);
INSERT INTO `list` VALUES ('in my youth', 17, 'リリィ、さよなら。 (Lily Sayonara)', 54);
INSERT INTO `list` VALUES ('つつみ込むように... (深情包围)', 17, 'MISIA (米希亚)', 55);
INSERT INTO `list` VALUES ('センス・オブ・ワンダー (Sense of Wonder)', 17, 'sumika', 56);
INSERT INTO `list` VALUES ('Till the End', 17, 'ReoNa· 刀剑神域刊行十周年纪念主题曲', 57);
INSERT INTO `list` VALUES ('叶问', 17, '川井宪次 (かわい けんじ)· 《叶问4》电影配乐', 58);
INSERT INTO `list` VALUES ('金字塔', 17, 'Reol (れをる)', 59);
INSERT INTO `list` VALUES ('Black Catcher', 17, 'ビッケブランカ (VICKEBLANKA)· 《黑色五叶草》TV动画片头曲', 60);
INSERT INTO `list` VALUES ('From The Seeds', 17, '上白石萌音· 《7SEEDS 第二季》Web动画片头曲', 61);
INSERT INTO `list` VALUES ('HBD', 17, '女王蜂 (じょおうばち)', 62);
INSERT INTO `list` VALUES ('I\'m a slave for you', 17, '川口レイジ (Reiji Kawaguchi)· 《这个男人是我人生中最大的错误》日剧主题曲', 64);
INSERT INTO `list` VALUES ('Driver', 17, 'the engy (ジ・エンギー)· 《心动讯号》日剧主题曲', 63);
INSERT INTO `list` VALUES ('Mozart: Piano Sonata No.2 in F, K.280 - 3. Presto', 17, 'Mitsuko Uchida', 65);
INSERT INTO `list` VALUES ('青空', 17, 'aiko (あいこ)', 66);
INSERT INTO `list` VALUES ('Higher', 17, 'SHE\'S· 第92回選抜高等学校野球大会 MBS公式テーマソング', 67);
INSERT INTO `list` VALUES ('STAYIN\' ALIVE', 17, 'JUJU (ジュジュ)· 《顶级手术刀-天才脑外科医生的条件》日剧主题曲', 68);
INSERT INTO `list` VALUES ('夢のような (如梦一般)', 17, '佐伯ユウスケ (saekiyouthk)· 《石纪元》TV动画片尾曲', 69);
INSERT INTO `list` VALUES ('BL', 17, '女王蜂 (じょおうばち)· 《10的秘密》日剧片头曲', 70);
INSERT INTO `list` VALUES ('ユニゾン (Unison)', 17, 'ClariS (クラリス)', 71);
INSERT INTO `list` VALUES ('無限大 (INFINITY)', 17, 'JO1 (ジェイオーワン)', 72);
INSERT INTO `list` VALUES ('Let\'s☆Go!! Girls', 17, '大黒摩季 (おおぐろ まき)', 73);
INSERT INTO `list` VALUES ('シリタイ', 17, 'SPICY CHOCOLATE (スパイシーチョコレート)/C&K (シーアンドケー)/CYBERJAPAN DANCERS', 74);
INSERT INTO `list` VALUES ('ポラリス (北极星)', 17, 'BLUE ENCOUNT (ブルーエンカウント)· 《我的英雄学院 第四季》TV动画片头曲', 76);
INSERT INTO `list` VALUES ('エスカルゴ (蜗牛)', 17, 'majiko (まじ娘)', 75);
INSERT INTO `list` VALUES ('ワスレナグサ (勿忘草)', 17, '蓮花 (れんか)', 77);
INSERT INTO `list` VALUES ('Sissy Sky', 17, '宮川愛李· 《名侦探柯南》TV动画片尾曲', 78);
INSERT INTO `list` VALUES ('チューリングラブ (Turing Love)', 17, 'ナナヲアカリ (Nanawoakari)/Sou· 《理科生坠入情网故尝试证明》TV动画片尾曲', 79);
INSERT INTO `list` VALUES ('シグナル (信号)', 17, 'ClariS (クラリス)· 《魔法纪录 魔法少女小圆外传:集结的百祸篇》游戏印象曲', 80);
INSERT INTO `list` VALUES ('Your Light', 17, 'milet (ミレイ)', 82);
INSERT INTO `list` VALUES ('Silence', 17, '久石让 (ひさいし じょう)', 81);
INSERT INTO `list` VALUES ('トロイの馬', 17, 'majiko (まじ娘)', 83);
INSERT INTO `list` VALUES ('チューリップ (郁金香)', 17, 'indigo la End (インディゴ ラ エンド)', 84);
INSERT INTO `list` VALUES ('STOP', 17, '川口レイジ (Reiji Kawaguchi)· 《这个男人是我人生中最大的错误》日剧片尾曲', 85);
INSERT INTO `list` VALUES ('New Page', 17, 'INTERSECTION (交差点)· 《黑色五叶草》TV动画片尾曲', 86);
INSERT INTO `list` VALUES ('ありがとうはこっちの言葉 (谢谢是我要说的话) (TV version)', 17, '森山直太朗 (もりやま なおたろう)· 《索玛丽与森林之神》TV动画片头曲', 87);
INSERT INTO `list` VALUES ('窓辺の即興曲 (窗边的即兴曲)', 17, 'オワタP (OwataP)/初音未来 (初音ミク)', 88);
INSERT INTO `list` VALUES ('ムズイ', 17, '22/7· 《22/7》TV动画片头曲', 89);
INSERT INTO `list` VALUES ('Kiki\'s Delivery Service', 17, '久石让 (ひさいし じょう)', 90);
INSERT INTO `list` VALUES ('Play the world', 17, '佐々木李子 (ささき りこ)· 《因为太怕痛就全点防御力了》TV动画片尾曲', 91);
INSERT INTO `list` VALUES ('光の道標 (光之路标)', 17, '鹿乃 (かの)· 《碧蓝航线》TV动画片尾曲', 92);
INSERT INTO `list` VALUES ('P R I D E', 17, '女王蜂 (じょおうばち)', 93);
INSERT INTO `list` VALUES ('あの日の未来', 17, 'リリィ、さよなら。 (Lily Sayonara)', 94);
INSERT INTO `list` VALUES ('星が降るユメ (繁星降落之梦)', 17, '蓝井艾露 (藍井エイル)· 《Fate/Grand Order -绝对魔兽战线巴比伦尼亚-》TV动画片尾曲', 95);
INSERT INTO `list` VALUES ('丸の内サディスティック', 17, '椎名林檎 (しいな りんご)', 97);
INSERT INTO `list` VALUES ('ユーモア (幽默)', 17, 'King Gnu (キング・ヌー)', 96);
INSERT INTO `list` VALUES ('Runnin\' feat. kZm, SIRUP', 17, 'BIM/kZm/SIRUP (シラップ)', 98);
INSERT INTO `list` VALUES ('サンサーラ (轮回)', 17, 'majiko (まじ娘)', 99);
INSERT INTO `list` VALUES ('够爱', 4, '胜屿', 4);
INSERT INTO `list` VALUES ('End of Time', 4, 'K-391/Alan Walker/Ahrix', 5);
INSERT INTO `list` VALUES ('我这一生', 4, '小曼', 6);
INSERT INTO `list` VALUES ('Will You Marry Me', 4, '一口甜', 7);
INSERT INTO `list` VALUES ('我这一生', 4, '马健涛', 8);
INSERT INTO `list` VALUES ('给女孩（单曲）', 4, '李宇春', 9);
INSERT INTO `list` VALUES ('心愿便利贴', 4, '王欣宇', 10);
INSERT INTO `list` VALUES ('借 (Live)', 4, '毛不易', 11);
INSERT INTO `list` VALUES ('冬日', 4, '鞠婧祎', 12);
INSERT INTO `list` VALUES ('你是对的人', 4, '戚薇/李俊昊 (이준호)· 《爱情回来了》电视剧片尾曲|《天天炫舞》背景音乐', 13);
INSERT INTO `list` VALUES ('春娇与志明', 4, '街道办GDC/欧阳耀莹', 14);
INSERT INTO `list` VALUES ('Monsters', 4, 'Katie Sky', 15);
INSERT INTO `list` VALUES ('后继者', 4, '任然', 16);
INSERT INTO `list` VALUES ('每个人都是孤独的', 4, '苏晗', 17);
INSERT INTO `list` VALUES ('惊雷', 4, 'MC阳子', 18);
INSERT INTO `list` VALUES ('夜空中最亮的星', 4, '逃跑计划', 19);
INSERT INTO `list` VALUES ('海月之端', 4, '双笙', 20);
INSERT INTO `list` VALUES ('盗墓笔记·十年人间', 4, '李常超· 八一七稻米节主题推广曲', 21);
INSERT INTO `list` VALUES ('WANNABE', 4, 'ITZY (있지)', 22);
INSERT INTO `list` VALUES ('Dancing With Your Ghost', 4, 'Sasha Sloan', 23);
INSERT INTO `list` VALUES ('因为我们在一起', 4, '王一博', 24);
INSERT INTO `list` VALUES ('王源：快跟着我进入文物的时空漫游吧！', 4, '王源', 25);
INSERT INTO `list` VALUES ('我这一生', 4, '半吨兄弟', 26);
INSERT INTO `list` VALUES ('红黑', 4, '小星星Aurora', 27);
INSERT INTO `list` VALUES ('Manta', 4, '刘柏辛Lexie', 28);
INSERT INTO `list` VALUES ('这就是爱吗？', 4, '容祖儿', 29);
INSERT INTO `list` VALUES ('Coming Home', 4, 'Diddy-Dirty Money/Skylar Grey', 30);
INSERT INTO `list` VALUES ('敢爱敢做', 4, '林子祥· 《神奇两女侠》电影主题曲', 31);
INSERT INTO `list` VALUES ('天空之外', 4, '解语花', 32);
INSERT INTO `list` VALUES ('让我欢喜让我忧', 4, '杨小壮/鹏鹏', 33);
INSERT INTO `list` VALUES ('迷人的危险', 4, '馅儿/neko', 34);
INSERT INTO `list` VALUES ('孤单的人', 4, '海来阿木', 35);
INSERT INTO `list` VALUES ('十年', 4, '陈奕迅· 《明年今日》国语版|《隐婚男女》电影插曲|《摆渡人》电影插曲', 36);
INSERT INTO `list` VALUES ('无人之岛', 4, '任然', 37);
INSERT INTO `list` VALUES ('无心斗艳', 4, '大布/苏泽龙', 38);
INSERT INTO `list` VALUES ('太阳 (女生版)', 4, '吕口口', 39);
INSERT INTO `list` VALUES ('年少有为 (Cover李荣浩)', 4, '酷', 40);
INSERT INTO `list` VALUES ('Sold Out', 4, 'Hawk Nelson', 41);
INSERT INTO `list` VALUES ('口是心非', 4, '杨小壮/鹏鹏', 42);
INSERT INTO `list` VALUES ('영웅 (英雄; Kick It)', 4, 'NCT 127 (엔씨티 127)', 43);
INSERT INTO `list` VALUES ('分手的话', 4, '苏谭谭', 44);
INSERT INTO `list` VALUES ('想你', 4, '艾辰', 45);
INSERT INTO `list` VALUES ('自己', 4, '刘亦菲· 电影《花木兰》中文主题曲', 46);
INSERT INTO `list` VALUES ('房间', 4, '刘瑞琦', 47);
INSERT INTO `list` VALUES ('平安回来', 4, '景甜/谭松韵/白宇', 49);
INSERT INTO `list` VALUES ('火苗 (男生版)', 4, '王不难', 48);
INSERT INTO `list` VALUES ('你走以后1.0', 4, '王恩信Est/二胖u', 50);
INSERT INTO `list` VALUES ('下凡', 4, '祝眠', 51);
INSERT INTO `list` VALUES ('好的 晚安 (Live)', 4, '邓见超', 54);
INSERT INTO `list` VALUES ('NUMB', 4, 'XXXTentacion', 52);
INSERT INTO `list` VALUES ('言不由衷', 4, '徐佳莹', 53);
INSERT INTO `list` VALUES ('你说的以后', 4, '蒋雪儿', 55);
INSERT INTO `list` VALUES ('红色高跟鞋', 4, '蔡健雅· 《爱情左右》电影主题曲', 56);
INSERT INTO `list` VALUES ('苏幕遮', 4, '张晓棠', 57);
INSERT INTO `list` VALUES ('U Make Me (Natan Chaim & Asketa Remix)', 4, 'Disco Fries/Raquel Castro', 58);
INSERT INTO `list` VALUES ('据说真的有神', 4, '木秦', 59);
INSERT INTO `list` VALUES ('二十岁的遗言', 4, '陈思键', 60);
INSERT INTO `list` VALUES ('豆浆油条', 4, '林俊杰· 《医馆笑传2》电视剧插曲', 61);
INSERT INTO `list` VALUES ('心欲止水', 4, '张碧晨· 《三生三世枕上书》电视剧插曲', 63);
INSERT INTO `list` VALUES ('最美的伤口', 4, '半吨兄弟', 62);
INSERT INTO `list` VALUES ('父亲写的散文诗 (时光版)', 4, '许飞', 64);
INSERT INTO `list` VALUES ('어떤 말도 (No Words)', 4, 'Crush (크러쉬)· 《梨泰院Class》韩剧插曲', 65);
INSERT INTO `list` VALUES ('Loyal Brave True (From \"Mulan\")', 4, 'Christina Aguilera', 66);
INSERT INTO `list` VALUES ('Who (feat. BTS)', 4, 'Lauv/BTS (防弹少年团)', 67);
INSERT INTO `list` VALUES ('挪威的森林', 4, '伍佰', 68);
INSERT INTO `list` VALUES ('시작 (开始)', 4, 'Gaho (가호)· 《梨泰院Class》韩剧插曲', 69);
INSERT INTO `list` VALUES ('关键词', 4, '林俊杰', 70);
INSERT INTO `list` VALUES ('天后', 4, '陈势安· 《面具》国语版', 71);
INSERT INTO `list` VALUES ('清明上河图', 4, '李玉刚', 72);
INSERT INTO `list` VALUES ('꿈 (Boom) (梦)', 4, 'NCT 127 (엔씨티 127)', 73);
INSERT INTO `list` VALUES ('我要找到你', 4, '连音社', 74);
INSERT INTO `list` VALUES ('消愁 (Live)', 4, '毛不易', 75);
INSERT INTO `list` VALUES ('以后的以后', 4, '庄心妍', 76);
INSERT INTO `list` VALUES ('我要找到你', 4, '小阿枫', 77);
INSERT INTO `list` VALUES ('黄沙', 4, '名决', 78);
INSERT INTO `list` VALUES ('秘语', 4, '欧阳娜娜/陈飞宇· 《秘果》电影悸动版推广曲', 79);
INSERT INTO `list` VALUES ('Elevator (127F)', 4, 'NCT 127 (엔씨티 127)', 80);
INSERT INTO `list` VALUES ('Turn All the Lights On', 4, 'T-Pain/Ne-Yo', 81);
INSERT INTO `list` VALUES ('快醒醒', 4, '黄晨晨', 82);
INSERT INTO `list` VALUES ('Touch The Sky', 4, 'Cedric Gervais/Digital Farm Animals/Dallas Austin', 83);
INSERT INTO `list` VALUES ('DJDJ给我一条K (抖音完整版)', 4, '新旭', 84);
INSERT INTO `list` VALUES ('老街', 4, '李荣浩', 86);
INSERT INTO `list` VALUES ('来生再去拥抱你', 4, '一只舟', 85);
INSERT INTO `list` VALUES ('我爱他', 4, '王小帅', 87);
INSERT INTO `list` VALUES ('来我怀里', 4, 'Smeng', 88);
INSERT INTO `list` VALUES ('再见只是陌生人', 4, '庄心妍', 89);
INSERT INTO `list` VALUES ('年少有为', 4, '李荣浩', 90);
INSERT INTO `list` VALUES ('奢香夫人', 4, '凤凰传奇', 91);
INSERT INTO `list` VALUES ('今生相爱', 4, '泽尔丹/扎西措', 92);
INSERT INTO `list` VALUES ('演员', 4, '薛之谦', 93);
INSERT INTO `list` VALUES ('后会无期', 4, 'G.E.M. 邓紫棋· 《后会无期》电影同名主题歌|《The End Of The World》中文版', 94);
INSERT INTO `list` VALUES ('Monsters', 4, 'Timeflies/Katie Sky', 95);
INSERT INTO `list` VALUES ('TING TING TING with Oliver Heldens', 4, 'ITZY (있지)/Oliver Heldens', 96);
INSERT INTO `list` VALUES ('不是因为寂寞才想你', 4, '王小帅', 97);
INSERT INTO `list` VALUES ('Love Story', 4, 'Taylor Swift', 98);
INSERT INTO `list` VALUES ('丫头', 4, '王童语· 《多少爱，可以重来》电视剧插曲', 99);
INSERT INTO `list` VALUES ('出征（大风歌）', 58, '宝石Gem', 3);
INSERT INTO `list` VALUES ('差不多姑娘', 58, 'G.E.M. 邓紫棋', 4);
INSERT INTO `list` VALUES ('两个普普通通小青年', 58, '李荣浩/刘柏辛Lexie', 5);
INSERT INTO `list` VALUES ('贰叁', 58, '吴亦凡', 6);
INSERT INTO `list` VALUES ('当渣男你不配', 58, 'coco这个李文', 7);
INSERT INTO `list` VALUES ('Don’t Wanna Lie (feat. 8lak, Hosea)', 58, '派伟俊/8lak/Hosea', 8);
INSERT INTO `list` VALUES ('野狼Disco (国风版)', 58, 'SING女团', 9);
INSERT INTO `list` VALUES ('生来如此', 58, '福克斯', 10);
INSERT INTO `list` VALUES ('归山', 58, '福克斯', 11);
INSERT INTO `list` VALUES ('玫瑰星云 Holy', 58, '刘柏辛Lexie', 12);
INSERT INTO `list` VALUES ('角儿无大小', 58, '十一少年的秋天/R1SE', 13);
INSERT INTO `list` VALUES ('空城', 58, 'KIT翌', 14);
INSERT INTO `list` VALUES ('失眠', 58, 'Ice Paper', 15);
INSERT INTO `list` VALUES ('第一顺位', 58, '吴亦凡/杨和苏KeyNG', 16);
INSERT INTO `list` VALUES ('浮云', 58, '任嘉伦', 17);
INSERT INTO `list` VALUES ('镜子', 58, '直火帮XZT/直火帮StraightFireGang', 18);
INSERT INTO `list` VALUES ('潘洛斯阶梯 Penrose', 58, '刘柏辛Lexie', 19);
INSERT INTO `list` VALUES ('野狼Disco (吃鸡版)', 58, '宝石Gem/沫子Mozz', 20);
INSERT INTO `list` VALUES ('summer holiday', 58, 'Young T', 21);
INSERT INTO `list` VALUES ('有空一起吃饭 (问候版)', 58, '新裤子/GAI', 22);
INSERT INTO `list` VALUES ('超能力', 58, 'Ice Paper', 23);
INSERT INTO `list` VALUES ('玩家的战歌', 58, '艾福杰尼· 《穿越火线：枪战王者》四周年主题曲', 24);
INSERT INTO `list` VALUES ('哎', 58, '黄子韬/韬斯曼', 25);
INSERT INTO `list` VALUES ('风吹草动', 58, '吴亦凡/大傻DamnShine', 26);
INSERT INTO `list` VALUES ('不是你的错', 58, '满舒克/董又霖', 27);
INSERT INTO `list` VALUES ('当你从没来过 pt.3', 58, 'StickyT/Over $ize', 28);
INSERT INTO `list` VALUES ('巾帼木兰', 58, 'VaVa毛衍七· 《部落冲突》巾帼木兰皮肤主题曲', 29);
INSERT INTO `list` VALUES ('Miss Me', 58, '王鹤棣/Ty.', 30);
INSERT INTO `list` VALUES ('城市烟火', 58, '王自健/丁嘉乐（Real Rascal）· 《安家》电视剧片头曲', 31);
INSERT INTO `list` VALUES ('也许这就是长大', 58, '爆音BOOM', 32);
INSERT INTO `list` VALUES ('Million Swag', 58, '黄旭', 33);
INSERT INTO `list` VALUES ('2020全都要稳', 58, '永彬Ryan.B', 34);
INSERT INTO `list` VALUES ('街头霸王', 58, '新秀', 35);
INSERT INTO `list` VALUES ('如果（If..）', 58, 'BOY STORY', 36);
INSERT INTO `list` VALUES ('肥龙过江', 58, '甄子丹/Jasmine Yen· 《肥龙过江》电影宣传曲', 37);
INSERT INTO `list` VALUES ('雨季', 58, '王齐铭WatchMe', 38);
INSERT INTO `list` VALUES ('Forever Young (ft. 福克斯)', 58, 'AR（刘夫阳）/福克斯', 39);
INSERT INTO `list` VALUES ('孤独行刑者 (刺客版)', 58, 'JX3暗箱组合· 剑网3凌雪藏锋版本宣传曲', 40);
INSERT INTO `list` VALUES ('催婚', 58, '孙八一', 41);
INSERT INTO `list` VALUES ('希望', 58, 'AR（刘夫阳）/Q.luv', 42);
INSERT INTO `list` VALUES ('黑暗中闪烁', 58, '8点组乐团', 43);
INSERT INTO `list` VALUES ('异地恋', 58, 'Max马俊', 44);
INSERT INTO `list` VALUES ('COLORFUL', 58, '娄峻硕', 45);
INSERT INTO `list` VALUES ('凌晨五点', 58, 'L4WUDU', 46);
INSERT INTO `list` VALUES ('如果真的我想要', 58, '黄旭', 47);
INSERT INTO `list` VALUES ('China Town', 58, 'Kigga/派克特', 49);
INSERT INTO `list` VALUES ('不退', 58, '杨和苏KeyNG· 《魔域》热血战歌', 48);
INSERT INTO `list` VALUES ('最冷的一天', 59, '谢东闵· 《庆余年》粤语版电视剧主题曲', 3);
INSERT INTO `list` VALUES ('我不是她', 59, 'HANA菊梓乔· 《法证先锋IV》电视剧片尾曲', 4);
INSERT INTO `list` VALUES ('圆谎', 59, '侧田· 《法证先锋IV》电视剧主题曲', 6);
INSERT INTO `list` VALUES ('Mad', 59, 'AGA', 7);
INSERT INTO `list` VALUES ('低半度', 59, '卫兰', 5);
INSERT INTO `list` VALUES ('不要流泪', 59, '郑俊弘· 《法证先锋IV》电视剧主题曲', 8);
INSERT INTO `list` VALUES ('嫁给爱情', 59, '杨千嬅· 《多功能老婆》电视剧主题曲', 9);
INSERT INTO `list` VALUES ('很久以后', 59, 'G.E.M. 邓紫棋· 《可不可以，你也刚好喜欢我》电影主题曲', 10);
INSERT INTO `list` VALUES ('那些没说出口的话', 59, '容祖儿· 《完美关系》电视剧情感主题曲', 11);
INSERT INTO `list` VALUES ('透明', 59, 'G.E.M. 邓紫棋', 12);
INSERT INTO `list` VALUES ('摩天动物园', 59, 'G.E.M. 邓紫棋', 13);
INSERT INTO `list` VALUES ('中华民族', 59, '莫文蔚/韩磊/谭维维/孙楠', 14);
INSERT INTO `list` VALUES ('似水流年', 59, '吴若希· 《大酱园》电视剧片尾曲', 15);
INSERT INTO `list` VALUES ('阿兹与海默', 59, '黎晓阳', 16);
INSERT INTO `list` VALUES ('果子', 59, '卢冠廷', 17);
INSERT INTO `list` VALUES ('亲密距离', 59, '刘美君', 18);
INSERT INTO `list` VALUES ('真心不变', 59, '谭嘉仪· 《大酱园》电视剧主题曲', 19);
INSERT INTO `list` VALUES ('没身份妒忌', 59, '胡鸿钧', 20);
INSERT INTO `list` VALUES ('日光', 59, '梁钊峰/陈仕燊', 21);
INSERT INTO `list` VALUES ('今宵多珍重', 59, '谭嘉仪· 《金宵大厦》剧集主题曲', 22);
INSERT INTO `list` VALUES ('你喜欢说谎', 59, 'HANA菊梓乔· 《黄金有罪》电视剧片尾曲', 23);
INSERT INTO `list` VALUES ('玩具成熟时', 59, '吴业坤', 24);
INSERT INTO `list` VALUES ('找到一个人', 59, '曾乐彤', 25);
INSERT INTO `list` VALUES ('喜剧收场', 59, '洪卓立', 26);
INSERT INTO `list` VALUES ('快闪', 59, '郑俊弘· 《黄金有罪》电视剧主题曲', 27);
INSERT INTO `list` VALUES ('零分', 59, 'JUDE曾若华', 28);
INSERT INTO `list` VALUES ('上善若水', 59, '黄子华/农夫· 《乜代宗师》电影主题曲', 29);
INSERT INTO `list` VALUES ('差不多姑娘', 59, 'G.E.M. 邓紫棋', 30);
INSERT INTO `list` VALUES ('透明的存在', 59, '许靖韵· 《完美关系》电视剧插曲', 31);
INSERT INTO `list` VALUES ('Walk on Water', 59, 'G.E.M. 邓紫棋· 《终结者：黑暗命运》电影中国区主题曲', 32);
INSERT INTO `list` VALUES ('一秒', 59, '林欣彤', 33);
INSERT INTO `list` VALUES ('说分手', 59, '连诗雅', 34);
INSERT INTO `list` VALUES ('最后晚餐 (2019)', 59, 'Supper Moment', 35);
INSERT INTO `list` VALUES ('我为我坚强', 59, '谷娅溦· 《独孤皇后》电视剧主题曲', 36);
INSERT INTO `list` VALUES ('Two at a time', 59, 'AGA', 37);
INSERT INTO `list` VALUES ('拼命无恙', 59, '林家谦', 38);
INSERT INTO `list` VALUES ('造就更好', 59, '容祖儿', 39);
INSERT INTO `list` VALUES ('是你令我再次找到心跳 (2019)', 59, 'Supper Moment', 40);
INSERT INTO `list` VALUES ('愿留住你 (Can You Hear 广东合唱版)', 59, '谭嘉仪/马国明', 41);
INSERT INTO `list` VALUES ('每段爱还是错', 59, '吴若希· 《多功能老婆》电视剧插曲', 42);
INSERT INTO `list` VALUES ('高攀爱', 59, '李靖筠· 《我的笋盘男友》电影主题曲', 43);
INSERT INTO `list` VALUES ('最安静的时候 (2019)', 59, 'Supper Moment', 44);
INSERT INTO `list` VALUES ('天光前分手', 59, '戴祖仪· 《多功能老婆》电视剧插曲', 45);
INSERT INTO `list` VALUES ('P.S. I Love You (2019)', 59, 'Supper Moment', 46);
INSERT INTO `list` VALUES ('将心比己', 59, '许廷铿', 47);
INSERT INTO `list` VALUES ('相信一切是最好的安排', 59, '陈蕾', 48);
INSERT INTO `list` VALUES ('平安夜 (打打气版)', 59, '梁咏琪', 50);
INSERT INTO `list` VALUES ('逆光飞翔', 59, 'HANA菊梓乔· 《凤弈》 电视剧主题曲', 49);
INSERT INTO `list` VALUES ('想勇敢一次', 59, '谭嘉仪· 《丫鬟大联盟》电视剧主题曲', 51);
INSERT INTO `list` VALUES ('初音', 59, '林二汶', 52);
INSERT INTO `list` VALUES ('冷处理', 59, '陈凯彤', 53);
INSERT INTO `list` VALUES ('黑方格', 59, '林奕匡/Artem Konstantinov', 54);
INSERT INTO `list` VALUES ('爱不起', 59, '王浩信· 《解决师》电视剧片尾曲', 55);
INSERT INTO `list` VALUES ('爱斯基摩人之吻', 59, '冯允谦', 56);
INSERT INTO `list` VALUES ('仙水', 59, '罗力威', 57);
INSERT INTO `list` VALUES ('了解中', 59, '卫诗', 58);
INSERT INTO `list` VALUES ('我说不可以', 59, '洪嘉豪', 60);
INSERT INTO `list` VALUES ('爱没怀疑', 59, '吴浩康', 59);
INSERT INTO `list` VALUES ('未知道', 59, '陈健安', 61);
INSERT INTO `list` VALUES ('你可能未必不喜欢我', 59, '许廷铿', 62);
INSERT INTO `list` VALUES ('逃生门 (门外版)', 59, '周国贤/王灏儿', 63);
INSERT INTO `list` VALUES ('有你有我 (2019)', 59, 'Supper Moment', 65);
INSERT INTO `list` VALUES ('最后的一个收费亭', 59, '陈柏宇', 64);
INSERT INTO `list` VALUES ('人魂道', 59, 'ToNick· 倩女幽魂2游戏主题曲', 66);
INSERT INTO `list` VALUES ('世事何曾是绝对', 59, '谭嘉仪', 67);
INSERT INTO `list` VALUES ('附近的人', 59, 'Yellow!', 68);
INSERT INTO `list` VALUES ('寻找白金汉 (合唱版)', 59, '冯允谦/黄淑蔓', 69);
INSERT INTO `list` VALUES ('Dear Christmas', 59, 'Dear Jane', 70);
INSERT INTO `list` VALUES ('今夜酒气吹过 (2019)', 59, 'Supper Moment', 71);
INSERT INTO `list` VALUES ('星空漫步 (Can You See 广东版)', 59, '谭嘉仪', 72);
INSERT INTO `list` VALUES ('刮骨', 59, '黄妍', 76);
INSERT INTO `list` VALUES ('面对', 59, '卫兰', 73);
INSERT INTO `list` VALUES ('懂得快乐 (2019)', 59, 'Supper Moment', 74);
INSERT INTO `list` VALUES ('我会想念他', 59, '何雁诗· 《牛下女高音》电视剧片尾曲', 75);
INSERT INTO `list` VALUES ('爸爸的礼物', 59, '陈柏宇', 77);
INSERT INTO `list` VALUES ('头顶有角', 59, '关智斌/黄宇希', 78);
INSERT INTO `list` VALUES ('荒废之绿洲', 59, '许廷铿', 80);
INSERT INTO `list` VALUES ('等等… (2019)', 59, 'Supper Moment', 79);
INSERT INTO `list` VALUES ('很久没拥抱 (2019)', 59, 'Supper Moment', 81);
INSERT INTO `list` VALUES ('奔向未来日子 (电影\"英雄本色续集\"主题曲)', 59, '张国荣', 82);
INSERT INTO `list` VALUES ('游乐 (粤语版)', 59, '陈明憙Jocelyn', 83);
INSERT INTO `list` VALUES ('Goodnight City (2019)', 59, 'Supper Moment', 84);
INSERT INTO `list` VALUES ('望', 59, '方皓玟', 85);
INSERT INTO `list` VALUES ('天知', 59, '梁钊峰/陈健安· 《解决师》电视剧主题曲', 86);
INSERT INTO `list` VALUES ('阿郎恋曲 (电影《阿郎的故事》歌曲)', 59, '许冠杰', 87);
INSERT INTO `list` VALUES ('最紧要好玩 (电影《打工皇帝》主题曲)', 59, '许冠杰', 88);
INSERT INTO `list` VALUES ('沙燕之歌 (2019)', 59, 'Supper Moment', 89);
INSERT INTO `list` VALUES ('家门', 59, '卫兰/冯允谦', 90);
INSERT INTO `list` VALUES ('譲我跟你走', 59, '叶丽仪', 91);
INSERT INTO `list` VALUES ('Lonely (广东版)', 59, '谭嘉仪', 92);
INSERT INTO `list` VALUES ('闲话当年', 59, '叶丽仪', 93);
INSERT INTO `list` VALUES ('永恒少年', 59, '曾乐彤', 94);
INSERT INTO `list` VALUES ('第千次重逢', 59, '李靖筠', 95);
INSERT INTO `list` VALUES ('肥皂泡 (2019)', 59, 'Supper Moment', 96);
INSERT INTO `list` VALUES ('桥下十三郎', 59, '陈柏宇', 97);
INSERT INTO `list` VALUES ('音乐说故事 (第一集 电脑)', 59, '梁咏琪/涂毓麟', 98);
INSERT INTO `list` VALUES ('重读兴趣班', 59, '林奕匡', 99);
INSERT INTO `list` VALUES ('Amazing（迷人的你）', 61, '林世民· 《下一站是幸福》电视剧片尾曲', 4);
INSERT INTO `list` VALUES ('安和', 61, '苏慧伦', 6);
INSERT INTO `list` VALUES ('一样美丽 (同心版)', 61, '周兴哲/黄妍/林奕匡/E.Viewz/Sezairi/陈柏宇/Benjamin Kheng/Ben&Ben/郑心慈/Narelle/陈明憙Jocelyn/NYK/Hà Lê/Wafa Bahiyya Haneesa/Fatin', 5);
INSERT INTO `list` VALUES ('温柔 #MaydayBlue20th', 61, '五月天/孙燕姿', 7);
INSERT INTO `list` VALUES ('Forever Your Dad', 61, '王力宏', 8);
INSERT INTO `list` VALUES ('一心一念', 61, '欧阳娜娜· 《北灵少年志之大主宰》电视剧片尾曲', 9);
INSERT INTO `list` VALUES ('悬日', 61, '田馥甄', 10);
INSERT INTO `list` VALUES ('I’m Falling in Love', 61, '郭静/宁桓宇· 《少主且慢行》电视剧插曲', 12);
INSERT INTO `list` VALUES ('气温37度的遐想', 61, '苏慧伦/魏如萱', 13);
INSERT INTO `list` VALUES ('仰望', 61, '陈威全', 11);
INSERT INTO `list` VALUES ('永远的一天', 61, '苏慧伦', 14);
INSERT INTO `list` VALUES ('为你变成他', 61, '苏慧伦', 15);
INSERT INTO `list` VALUES ('你的影子是我的海', 61, '吴青峰· from 王小苗诗集《邪恶的纯真》pp.108-110.', 16);
INSERT INTO `list` VALUES ('Don’t Wanna Lie (feat. 8lak, Hosea)', 61, '派伟俊/8lak/Hosea', 17);
INSERT INTO `list` VALUES ('你会想念我吗', 61, '苏慧伦', 18);
INSERT INTO `list` VALUES ('量力而为', 61, '苏慧伦', 19);
INSERT INTO `list` VALUES ('烂醉', 61, '颜人中', 20);
INSERT INTO `list` VALUES ('远行', 61, '苏慧伦', 21);
INSERT INTO `list` VALUES ('你', 61, '毕书尽', 22);
INSERT INTO `list` VALUES ('坚信爱会赢', 61, '王力宏/田桐/成龙/李光洁/肖战/吴京/沈腾/宋佳/杨培安/张蕾/陈建斌/林永健/佟丽娅/海霞/黄晓明/舒楠/雷佳/谭维维', 23);
INSERT INTO `list` VALUES ('点亮一束光', 61, '陈志朋', 24);
INSERT INTO `list` VALUES ('与生俱来的黑', 61, '苏慧伦', 26);
INSERT INTO `list` VALUES ('亲爱的全部', 61, '苏慧伦', 25);
INSERT INTO `list` VALUES ('幸福特写', 61, '陈立农', 27);
INSERT INTO `list` VALUES ('背光旅行', 61, '黄伟晋', 28);
INSERT INTO `list` VALUES ('迷人的危险', 61, '蔡黄汝', 29);
INSERT INTO `list` VALUES ('红红的太阳', 61, '张韶涵', 30);
INSERT INTO `list` VALUES ('小时候的我们', 61, '周兴哲', 31);
INSERT INTO `list` VALUES ('我喜欢你', 61, '彭佳慧', 32);
INSERT INTO `list` VALUES ('像风', 61, '郭静· 《将夜2》影视剧插曲', 33);
INSERT INTO `list` VALUES ('Colorful', 61, '郭静· 《身为一个胖子》电视剧主题曲', 34);
INSERT INTO `list` VALUES ('少年', 61, '周华健', 35);
INSERT INTO `list` VALUES ('春到了', 61, '黄小琥', 36);
INSERT INTO `list` VALUES ('当你和心跳一起出现', 61, '萧亚轩', 38);
INSERT INTO `list` VALUES ('默念你', 61, '宋念宇', 37);
INSERT INTO `list` VALUES ('你的情歌', 61, 'Tank', 39);
INSERT INTO `list` VALUES ('在我成为井井有条的大人之前', 61, '郭采洁', 40);
INSERT INTO `list` VALUES ('Be Me', 61, '李玉玺', 41);
INSERT INTO `list` VALUES ('受够', 61, '周兴哲', 43);
INSERT INTO `list` VALUES ('爱永远', 61, '柯以敏', 42);
INSERT INTO `list` VALUES ('借我一生', 61, '张芸京· 《将夜2》影视剧插曲', 44);
INSERT INTO `list` VALUES ('我很快乐', 61, '周兴哲', 45);
INSERT INTO `list` VALUES ('情人节的许愿', 61, '阿沁', 46);
INSERT INTO `list` VALUES ('我一直都在这里', 61, '徐佳莹· 《熊出没·狂野大陆》电影主题曲', 47);
INSERT INTO `list` VALUES ('背光', 61, '杨宗纬· 《被光抓走的人》电影主题曲', 48);
INSERT INTO `list` VALUES ('七十亿分之一加一', 61, '吴卓源/娄峻硕', 49);
INSERT INTO `list` VALUES ('让爱逆行', 61, '郭品超/汪东城/辰亦儒', 50);
INSERT INTO `list` VALUES ('够不着的你', 61, '安心亚· 《坠爱》爱奇艺片尾曲', 51);
INSERT INTO `list` VALUES ('你钉起来真好听 (儿童版)', 61, '方冉星', 52);
INSERT INTO `list` VALUES ('梦里千回', 61, '徐怀钰· 《将夜2》影视剧插曲', 53);
INSERT INTO `list` VALUES ('民谣.唐', 61, '李佩玲· 《少年李白花月离》网络电影主题曲', 54);
INSERT INTO `list` VALUES ('带我去找夜生活', 61, '告五人', 55);
INSERT INTO `list` VALUES ('狂浪', 61, '彭于晏/王彦霖/辛芷蕾/王雨甜/徐洋/陈家乐/李岷城· 《紧急救援》电影宣传曲', 56);
INSERT INTO `list` VALUES ('离开我的依赖', 61, '王艳薇', 57);
INSERT INTO `list` VALUES ('流浪狗 (黄明志独唱版本)', 61, '黄明志', 58);
INSERT INTO `list` VALUES ('时间梯', 61, '万芳', 59);
INSERT INTO `list` VALUES ('COLORFUL', 61, '娄峻硕', 60);
INSERT INTO `list` VALUES ('逆行', 61, '张惠春/郝澄泉RogerQ', 61);
INSERT INTO `list` VALUES ('相信爱', 61, '周兴哲', 62);
INSERT INTO `list` VALUES ('大明星', 61, 'AJ张杰', 63);
INSERT INTO `list` VALUES ('Jay Chou - 双截棍 (Patrick Brasca Remix)', 61, '派伟俊', 64);
INSERT INTO `list` VALUES ('假装', 61, '梁一贞', 65);
INSERT INTO `list` VALUES ('泰国情哥 (亚洲通话新歌发布会现场版本)', 61, '黄明志', 66);
INSERT INTO `list` VALUES ('示爱嫌疑', 61, '董又霖', 67);
INSERT INTO `list` VALUES ('我知道你都知道', 61, '陈威全', 68);
INSERT INTO `list` VALUES ('请珍重', 61, '罗大佑', 70);
INSERT INTO `list` VALUES ('其实你并没那么孤单', 61, '周兴哲', 69);
INSERT INTO `list` VALUES ('女士优先(feat. ?te)', 61, '老莫/李怀特', 71);
INSERT INTO `list` VALUES ('In the Works', 61, '周兴哲', 72);
INSERT INTO `list` VALUES ('世界为你醒来 (好声音接力9)', 61, '刘明湘/李佩玲/黄一/关诗敏/陈颖恩/古洁萦/长宇/吕纬青/罗金荣/吴映香', 73);
INSERT INTO `list` VALUES ('上古情歌', 61, '齐豫· 《大明风华》电视剧插曲', 74);
INSERT INTO `list` VALUES ('我最骄傲爱过的人 (Demo版)', 61, '张简君伟', 75);
INSERT INTO `list` VALUES ('我知道', 61, 'CT2', 76);
INSERT INTO `list` VALUES ('无关幸福', 61, '曾静玟', 77);
INSERT INTO `list` VALUES ('不忘', 61, '范玮琪', 78);
INSERT INTO `list` VALUES ('江湖吾路 (霹雳侠峰片头曲)', 61, '刘昱贤/霹雳布袋戏', 79);
INSERT INTO `list` VALUES ('在名为未来的波浪里', 61, '原子邦妮', 80);
INSERT INTO `list` VALUES ('破晓', 61, '杨培安', 81);
INSERT INTO `list` VALUES ('天使爱大象', 61, '徐佳莹· 《极道千金》NETFLIX原创影集片尾曲', 82);
INSERT INTO `list` VALUES ('迷途 (相见版)', 61, '周华健', 83);
INSERT INTO `list` VALUES ('鲸落（Whale Fall）', 61, '林采欣', 84);
INSERT INTO `list` VALUES ('冰岛', 61, '周华健', 85);
INSERT INTO `list` VALUES ('Something About You', 61, '周兴哲', 86);
INSERT INTO `list` VALUES ('That\'s Why I Like You', 61, '周兴哲', 87);
INSERT INTO `list` VALUES ('Room for You', 61, '周兴哲', 88);
INSERT INTO `list` VALUES ('我陪你哭', 61, '陈威全', 89);
INSERT INTO `list` VALUES ('Rollercoasters', 61, '周兴哲', 90);
INSERT INTO `list` VALUES ('Me and You', 61, '周兴哲', 91);
INSERT INTO `list` VALUES ('U sTuPiD', 61, 'Karencici/ØZI', 92);
INSERT INTO `list` VALUES ('妈妈教会我', 61, '徐佳莹· from 王小苗诗集《邪恶的纯真》pp. 4-5.', 93);
INSERT INTO `list` VALUES ('CHEERIO', 61, '蔡佩轩', 94);
INSERT INTO `list` VALUES ('5 am', 61, '吴卓源', 95);
INSERT INTO `list` VALUES ('带我去找夜生活 - 健康版', 61, '告五人', 96);
INSERT INTO `list` VALUES ('欢欢喜喜过新年', 61, '董又霖/Casper卡斯柏/徐圣恩/谷蓝帝/丁飞俊/陆思恒', 97);
INSERT INTO `list` VALUES ('一首唱不红的歌', 61, 'AJ张杰', 98);
INSERT INTO `list` VALUES ('38F', 61, 'RPG', 99);
INSERT INTO `list` VALUES ('关键词', 60, '林俊杰', 5);
INSERT INTO `list` VALUES ('苏幕遮', 60, '张晓棠', 6);
INSERT INTO `list` VALUES ('Manta', 60, '刘柏辛Lexie', 4);
INSERT INTO `list` VALUES ('你是对的人', 60, '戚薇/李俊昊 (이준호)· 《爱情回来了》电视剧片尾曲|《天天炫舞》背景音乐', 8);
INSERT INTO `list` VALUES ('桥边姑娘', 60, '海伦', 7);
INSERT INTO `list` VALUES ('Dancing With Your Ghost', 60, 'Sasha Sloan', 9);
INSERT INTO `list` VALUES ('春娇与志明', 60, '街道办GDC/欧阳耀莹', 10);
INSERT INTO `list` VALUES ('十年', 60, '陈奕迅· 《明年今日》国语版|《隐婚男女》电影插曲|《摆渡人》电影插曲', 11);
INSERT INTO `list` VALUES ('晴天', 60, '周杰伦', 12);
INSERT INTO `list` VALUES ('无心斗艳', 60, '大布/苏泽龙', 13);
INSERT INTO `list` VALUES ('世界这么大还是遇见你', 60, '程响· 清新的小女孩（中文版）', 14);
INSERT INTO `list` VALUES ('光年之外', 60, 'G.E.M. 邓紫棋· 《太空旅客（Passengers）》电影中国区主题曲', 15);
INSERT INTO `list` VALUES ('七里香', 60, '周杰伦', 16);
INSERT INTO `list` VALUES ('无人之岛', 60, '任然', 17);
INSERT INTO `list` VALUES ('稻香', 60, '周杰伦', 18);
INSERT INTO `list` VALUES ('年少有为', 60, '李荣浩', 19);
INSERT INTO `list` VALUES ('冬眠', 60, '司南', 21);
INSERT INTO `list` VALUES ('莫问归期', 60, '蒋雪儿', 20);
INSERT INTO `list` VALUES ('只要平凡', 60, '张杰/张碧晨· 《我不是药神》电影主题曲', 22);
INSERT INTO `list` VALUES ('句号', 60, 'G.E.M. 邓紫棋', 23);
INSERT INTO `list` VALUES ('下山', 60, '要不要买菜', 24);
INSERT INTO `list` VALUES ('嚣张', 60, 'en', 25);
INSERT INTO `list` VALUES ('等你下课 (with 杨瑞代)', 60, '周杰伦', 26);
INSERT INTO `list` VALUES ('麻雀', 60, '李荣浩', 27);
INSERT INTO `list` VALUES ('体面', 60, '于文文· 《前任3：再见前任》电影插曲', 28);
INSERT INTO `list` VALUES ('像鱼', 60, '王贰浪', 29);
INSERT INTO `list` VALUES ('泡沫', 60, 'G.E.M. 邓紫棋', 30);
INSERT INTO `list` VALUES ('芒种', 60, '音阙诗听/赵方婧', 31);
INSERT INTO `list` VALUES ('你的答案', 60, '阿冗', 32);
INSERT INTO `list` VALUES ('红色高跟鞋', 60, '蔡健雅· 《爱情左右》电影主题曲', 33);
INSERT INTO `list` VALUES ('你的酒馆对我打了烊', 60, '陈雪凝', 34);
INSERT INTO `list` VALUES ('火红的萨日朗', 60, '要不要买菜', 35);
INSERT INTO `list` VALUES ('无赖', 60, '郑中基', 36);
INSERT INTO `list` VALUES ('50 Feet (Explicit)', 60, 'SoMo', 37);
INSERT INTO `list` VALUES ('我的名字', 60, '焦迈奇', 38);
INSERT INTO `list` VALUES ('火苗', 60, '苏晗', 39);
INSERT INTO `list` VALUES ('这一生关于你的风景', 60, '枯木逢春', 40);
INSERT INTO `list` VALUES ('那女孩对我说 (完整版)', 60, 'Uu', 41);
INSERT INTO `list` VALUES ('借 (Live)', 60, '毛不易', 42);
INSERT INTO `list` VALUES ('来自天堂的魔鬼', 60, 'G.E.M. 邓紫棋', 43);
INSERT INTO `list` VALUES ('遇见', 60, '孙燕姿· 《向左走，向右走》电影主题曲', 44);
INSERT INTO `list` VALUES ('一生与你擦肩而过', 60, '阿悠悠', 45);
INSERT INTO `list` VALUES ('想见你想见你想见你', 60, '八三夭乐团· 《想见你》电视剧片尾曲', 46);
INSERT INTO `list` VALUES ('无期', 60, '光头华夏', 47);
INSERT INTO `list` VALUES ('牧马城市', 60, '毛不易· 《老男孩》电视剧片尾曲', 48);
INSERT INTO `list` VALUES ('野狼disco', 60, '宝石Gem', 49);
INSERT INTO `list` VALUES ('画 (Live Piano Session Ⅱ)', 60, 'G.E.M. 邓紫棋', 50);
INSERT INTO `list` VALUES ('缘分一道桥', 60, '王力宏/谭维维· 《长城》电影片尾曲', 51);
INSERT INTO `list` VALUES ('修炼爱情', 60, '林俊杰', 52);
INSERT INTO `list` VALUES ('我走后', 60, '小咪', 53);
INSERT INTO `list` VALUES ('可不可以', 60, '张紫豪', 54);
INSERT INTO `list` VALUES ('贝贝', 60, '李荣浩', 55);
INSERT INTO `list` VALUES ('云烟成雨', 60, '房东的猫· 《我是江小白》动画片尾曲', 56);
INSERT INTO `list` VALUES ('绿色', 60, '陈雪凝', 57);
INSERT INTO `list` VALUES ('你是我唯一的执着', 60, '马健涛', 58);
INSERT INTO `list` VALUES ('溯 (Reverse) feat. 马吟吟', 60, 'CORSAK胡梦周/马吟吟', 59);
INSERT INTO `list` VALUES ('Faded', 60, 'Alan Walker/Iselin Solheim', 60);
INSERT INTO `list` VALUES ('心如止水', 60, 'Ice Paper', 61);
INSERT INTO `list` VALUES ('单车', 60, '陈奕迅', 62);
INSERT INTO `list` VALUES ('夜空中最亮的星', 60, '逃跑计划', 63);
INSERT INTO `list` VALUES ('多想在平庸的生活拥抱你 (Live)', 60, '隔壁老樊', 64);
INSERT INTO `list` VALUES ('勇气', 60, '棉子', 65);
INSERT INTO `list` VALUES ('一个人挺好', 60, '孟颖', 66);
INSERT INTO `list` VALUES ('安和桥', 60, '宋冬野', 67);
INSERT INTO `list` VALUES ('一个人挺好', 60, '杨小壮', 68);
INSERT INTO `list` VALUES ('演员', 60, '薛之谦', 69);
INSERT INTO `list` VALUES ('侧脸', 60, '于果', 70);
INSERT INTO `list` VALUES ('爱情堡垒 (DJ版)', 60, '杨小壮', 71);
INSERT INTO `list` VALUES ('追光者', 60, '岑宁儿· 《夏至未至》电视剧插曲', 73);
INSERT INTO `list` VALUES ('清新的小女孩', 60, 'July Tun', 72);
INSERT INTO `list` VALUES ('你笑起来真好看', 60, '李昕融（ariel  li）/樊桐舟/李凯稠', 74);
INSERT INTO `list` VALUES ('黎明前的黑暗 (Live)', 60, '张韶涵/王晰', 75);
INSERT INTO `list` VALUES ('可惜没如果', 60, '林俊杰· 《杜鹃之巢》韩剧中文主题曲|《对我而言，可爱的她》韩剧中文片尾曲', 76);
INSERT INTO `list` VALUES ('一曲相思', 60, '半阳', 77);
INSERT INTO `list` VALUES ('成都', 60, '赵雷', 78);
INSERT INTO `list` VALUES ('百花香', 60, '魏新雨', 79);
INSERT INTO `list` VALUES ('时间的过客', 60, '名决', 80);
INSERT INTO `list` VALUES ('太阳 (正式版)', 60, '曲肖冰', 81);
INSERT INTO `list` VALUES ('欧若拉', 60, '张韶涵', 82);
INSERT INTO `list` VALUES ('感谢你曾来过', 60, 'Ayo97/周思涵', 83);
INSERT INTO `list` VALUES ('琵琶行', 60, '奇然/沈谧仁', 84);
INSERT INTO `list` VALUES ('大眠 (Cover：王心凌)', 60, '王茗', 85);
INSERT INTO `list` VALUES ('你若三冬', 60, '阿悠悠', 86);
INSERT INTO `list` VALUES ('酒醉的蝴蝶', 60, '崔伟立', 87);
INSERT INTO `list` VALUES ('那些你很冒险的梦', 60, '林俊杰', 88);
INSERT INTO `list` VALUES ('海阔天空', 60, 'BEYOND', 89);
INSERT INTO `list` VALUES ('That Girl', 60, 'Olly Murs', 90);
INSERT INTO `list` VALUES ('红昭愿', 60, '音阙诗听', 91);
INSERT INTO `list` VALUES ('暗示分离', 60, 'en', 92);
INSERT INTO `list` VALUES ('山楂树の恋', 60, '程jiajia', 93);
INSERT INTO `list` VALUES ('空空如也', 60, '胡66', 94);
INSERT INTO `list` VALUES ('消愁 (Live)', 60, '毛不易', 95);
INSERT INTO `list` VALUES ('Hero', 60, 'Cash Cash/Christina Perri', 96);
INSERT INTO `list` VALUES ('再见只是陌生人', 60, '庄心妍', 97);
INSERT INTO `list` VALUES ('大雪', 60, '音阙诗听/王梓钰', 98);
INSERT INTO `list` VALUES ('许多年以后', 60, '赵鑫', 99);
INSERT INTO `list` VALUES ('都市丽人生存报告', 52, '大籽', 3);
INSERT INTO `list` VALUES ('风月梦', 52, '泥鳅Niko', 4);
INSERT INTO `list` VALUES ('早知道在家待这么久', 52, '张尕怂', 5);
INSERT INTO `list` VALUES ('晴空一尾鲤', 52, 'hanser', 7);
INSERT INTO `list` VALUES ('春山', 52, '子弥', 8);
INSERT INTO `list` VALUES ('美丽的遗憾', 52, '平凡的艾岩', 6);
INSERT INTO `list` VALUES ('2020～此间未来～', 52, '千月兔/封茗囧菌/等什么君/洛少爷/叶洛洛/双笙/Smile_小千/俺酱/奇然/笛呆子囚牛/妖蝠/洛劫/宗顺康/小连杀/执素兮/玄觞/只有影子/小时姑娘/叶里/千界SUMI/栩影酱/小吴太太/心然/醋醋/祈Inory/茶理理理子', 9);
INSERT INTO `list` VALUES ('渺渺', 52, '伦桑', 10);
INSERT INTO `list` VALUES ('山水墨', 52, '小曲儿', 11);
INSERT INTO `list` VALUES ('地铁上的陌生人', 52, '零6/陆怡雯', 12);
INSERT INTO `list` VALUES ('宅在家里的日子', 52, '马晓晨', 13);
INSERT INTO `list` VALUES ('逾期回忆（Feat.魏然）', 52, 'MOP17', 15);
INSERT INTO `list` VALUES ('波心月', 52, '萧忆情Alex', 14);
INSERT INTO `list` VALUES ('我想和你看夕阳', 52, '李甜', 16);
INSERT INTO `list` VALUES ('风起了', 52, 'Tie Yann (铁阳)', 17);
INSERT INTO `list` VALUES ('ᐇ', 52, 'W/', 18);
INSERT INTO `list` VALUES ('每一片落叶都知你名姓', 52, '西瓜JUN', 19);
INSERT INTO `list` VALUES ('穿行者', 52, '丁于/丫蛋蛋（马启涵）', 20);
INSERT INTO `list` VALUES ('其实', 52, '宋宇航', 21);
INSERT INTO `list` VALUES ('归山', 52, '福克斯', 22);
INSERT INTO `list` VALUES ('念故清欢', 52, '张十二', 23);
INSERT INTO `list` VALUES ('好久没见过', 52, '大喜', 24);
INSERT INTO `list` VALUES ('Careful', 52, '北一街', 25);
INSERT INTO `list` VALUES ('意料之外', 52, '赵晨唏', 26);
INSERT INTO `list` VALUES ('最甜情歌', 52, '高博深', 27);
INSERT INTO `list` VALUES ('等待天亮', 52, '钱润玉/FACEVÔID', 28);
INSERT INTO `list` VALUES ('小人物', 52, '赵雷', 29);
INSERT INTO `list` VALUES ('对悲观过于乐观', 52, '钟声', 30);
INSERT INTO `list` VALUES ('CHINA-新春', 52, '徐梦圆', 31);
INSERT INTO `list` VALUES ('水瓶先生', 52, '司徒赫伦', 32);
INSERT INTO `list` VALUES ('告白', 52, '一口甜', 33);
INSERT INTO `list` VALUES ('好好的', 52, '虎二', 34);
INSERT INTO `list` VALUES ('Planet', 52, '袁景翔', 35);
INSERT INTO `list` VALUES ('姐姐', 52, '贾盛强', 36);
INSERT INTO `list` VALUES ('热岛症', 52, '双笙', 37);
INSERT INTO `list` VALUES ('海棠 (纯音乐)', 52, 'Jin', 38);
INSERT INTO `list` VALUES ('凌晨两点的北京', 52, '谢宇伦', 39);
INSERT INTO `list` VALUES ('雨魅', 52, '孔柏森/杨胖雨', 40);
INSERT INTO `list` VALUES ('人间烟火', 52, '陈硕子', 41);
INSERT INTO `list` VALUES ('不是你的错', 52, '满舒克/董又霖', 42);
INSERT INTO `list` VALUES ('黑暗中闪烁', 52, '8点组乐团', 43);
INSERT INTO `list` VALUES ('其后', 52, '文兆杰', 44);
INSERT INTO `list` VALUES ('画中人', 52, '小魂', 45);
INSERT INTO `list` VALUES ('AM', 52, '李霄云', 46);
INSERT INTO `list` VALUES ('summer holiday', 52, 'Young T', 47);
INSERT INTO `list` VALUES ('当渣男你不配', 52, 'coco这个李文', 48);
INSERT INTO `list` VALUES ('等一树花开', 52, '简弘亦', 49);
INSERT INTO `list` VALUES ('我是你永远得不到的爸爸', 52, 'Q.luv/CLOUDWANG 王云/Ki.DAstronaut', 50);
INSERT INTO `list` VALUES ('LOU', 52, '尬倍儿 Gabier S.R.', 51);
INSERT INTO `list` VALUES ('温软宇宙', 52, 'Crazy Bucket/浮云心丶/Warma', 52);
INSERT INTO `list` VALUES ('胜利者', 52, '棉子', 53);
INSERT INTO `list` VALUES ('Million Swag', 52, '黄旭', 54);
INSERT INTO `list` VALUES ('青春记录号', 52, '街道办GDC/阿细', 55);
INSERT INTO `list` VALUES ('Turn me on', 52, '林嘉莹/玛尔斯Mars/霹雳杰瑞', 56);
INSERT INTO `list` VALUES ('炙热阳光 (S制造群星)', 52, '「S制造」群星/永彬Ryan.B/都智文/谢宇伦/崔天琪QiQi/麦吉_Maggie/洛松维/孟西/李艺玟Evan/丛琳潼elf/洛伊ChloeYin/江苹果', 57);
INSERT INTO `list` VALUES ('致陌生的你', 52, '河图', 58);
INSERT INTO `list` VALUES ('青玉案·元夕', 52, '赵景旭[Winky诗]', 59);
INSERT INTO `list` VALUES ('空城', 52, 'KIT翌', 60);
INSERT INTO `list` VALUES ('村花', 52, 'willen', 61);
INSERT INTO `list` VALUES ('他的夏', 52, 'LunaLiu刘不语', 62);
INSERT INTO `list` VALUES ('没有派对', 52, '方盒子', 63);
INSERT INTO `list` VALUES ('Catalyst', 52, 'Jiaye', 64);
INSERT INTO `list` VALUES ('镜子', 52, '直火帮XZT/直火帮StraightFireGang', 65);
INSERT INTO `list` VALUES ('Money', 52, 'Jason Chen', 66);
INSERT INTO `list` VALUES ('追梦', 52, 'LuckyMaxx', 68);
INSERT INTO `list` VALUES ('加油武汉 (Demo)', 52, '脑浊乐队', 67);
INSERT INTO `list` VALUES ('在我想你的时候', 52, 'Shang/Neil Chen/superluckyqi', 69);
INSERT INTO `list` VALUES ('等风停靠', 52, '袁野夕', 70);
INSERT INTO `list` VALUES ('众志成城 抗击疫情 (Demo)', 52, '4U乐队', 71);
INSERT INTO `list` VALUES ('侠客行 (Demo)', 52, '肖恩Shaun Gibson', 72);
INSERT INTO `list` VALUES ('锦书莫', 52, 'KBShinya', 73);
INSERT INTO `list` VALUES ('小院', 52, '暗杠', 74);
INSERT INTO `list` VALUES ('白色', 52, '牛佳钰', 75);
INSERT INTO `list` VALUES ('心头的刺', 52, '谣君', 76);
INSERT INTO `list` VALUES ('北半球', 52, '十豆彡', 77);
INSERT INTO `list` VALUES ('催婚', 52, '孙八一', 78);
INSERT INTO `list` VALUES ('千山写尽', 52, '潇梦临', 81);
INSERT INTO `list` VALUES ('旧友', 52, '银临', 79);
INSERT INTO `list` VALUES ('疫情结束后我们见面吧', 52, 'Gravi T', 80);
INSERT INTO `list` VALUES ('也许这就是长大', 52, '爆音BOOM', 82);
INSERT INTO `list` VALUES ('勿忘我', 52, '星弟', 83);
INSERT INTO `list` VALUES ('Escape', 52, 'A7i', 84);
INSERT INTO `list` VALUES ('不可理喻', 52, 'StickyT', 86);
INSERT INTO `list` VALUES ('忽然有一天我变得特别喜欢你', 52, '乔万旭', 85);
INSERT INTO `list` VALUES ('武汉加油！中国加油！', 52, '侯兵一', 88);
INSERT INTO `list` VALUES ('守候', 52, '布衣乐队/RN', 87);
INSERT INTO `list` VALUES ('总是不完美', 52, 'SycoTyrant', 89);
INSERT INTO `list` VALUES ('武汉加油', 52, '廉山', 91);
INSERT INTO `list` VALUES ('战疫', 52, 'HKG-嘻哈幼稚园', 90);
INSERT INTO `list` VALUES ('武汉别哭', 52, 'AeyE', 92);
INSERT INTO `list` VALUES ('不安', 52, '张北', 93);
INSERT INTO `list` VALUES ('52HZ', 52, 'Ellie', 94);
INSERT INTO `list` VALUES ('宣战', 52, '觉醒乐队/吴可', 95);
INSERT INTO `list` VALUES ('老三', 52, '排骨教主', 96);
INSERT INTO `list` VALUES ('别怕，我也在这里', 52, '苟瀚中/李代沫', 97);
INSERT INTO `list` VALUES ('夜行动物', 52, 'KEYI杨豪', 98);
INSERT INTO `list` VALUES ('因为你在', 52, '达闻西乐队/福禄寿FloruitShow', 99);
INSERT INTO `list` VALUES ('春娇与志明', 26, '街道办GDC/欧阳耀莹', 5);
INSERT INTO `list` VALUES ('Dancing With Your Ghost', 26, 'Sasha Sloan', 6);
INSERT INTO `list` VALUES ('麻雀', 26, '李荣浩', 7);
INSERT INTO `list` VALUES ('嚣张', 26, 'en', 8);
INSERT INTO `list` VALUES ('关键词', 26, '林俊杰', 9);
INSERT INTO `list` VALUES ('红色高跟鞋', 26, '蔡健雅· 《爱情左右》电影主题曲', 10);
INSERT INTO `list` VALUES ('苏幕遮', 26, '张晓棠', 11);
INSERT INTO `list` VALUES ('想见你想见你想见你', 26, '八三夭乐团· 《想见你》电视剧片尾曲', 12);
INSERT INTO `list` VALUES ('晴天', 26, '周杰伦', 13);
INSERT INTO `list` VALUES ('句号', 26, 'G.E.M. 邓紫棋', 14);
INSERT INTO `list` VALUES ('百花香', 26, '魏新雨', 15);
INSERT INTO `list` VALUES ('无期', 26, '光头华夏', 16);
INSERT INTO `list` VALUES ('我们', 26, '陈奕迅· 《后来的我们》电影主题曲', 17);
INSERT INTO `list` VALUES ('处处吻', 26, '杨千嬅', 18);
INSERT INTO `list` VALUES ('火红的萨日朗', 26, '要不要买菜', 19);
INSERT INTO `list` VALUES ('无人之岛', 26, '任然', 20);
INSERT INTO `list` VALUES ('芒种', 26, '音阙诗听/赵方婧', 21);
INSERT INTO `list` VALUES ('贝贝', 26, '李荣浩', 22);
INSERT INTO `list` VALUES ('会好的', 26, '张艺兴', 23);
INSERT INTO `list` VALUES ('体面', 26, '于文文· 《前任3：再见前任》电影插曲', 24);
INSERT INTO `list` VALUES ('勇气', 26, '棉子', 25);
INSERT INTO `list` VALUES ('那女孩对我说 (完整版)', 26, 'Uu', 26);
INSERT INTO `list` VALUES ('Monsters', 26, 'Katie Sky', 27);
INSERT INTO `list` VALUES ('光年之外', 26, 'G.E.M. 邓紫棋· 《太空旅客（Passengers）》电影中国区主题曲', 28);
INSERT INTO `list` VALUES ('十年', 26, '陈奕迅· 《明年今日》国语版|《隐婚男女》电影插曲|《摆渡人》电影插曲', 29);
INSERT INTO `list` VALUES ('Manta', 26, '刘柏辛Lexie', 30);
INSERT INTO `list` VALUES ('七里香', 26, '周杰伦', 31);
INSERT INTO `list` VALUES ('让我欢喜让我忧', 26, '杨小壮/鹏鹏', 33);
INSERT INTO `list` VALUES ('年少有为', 26, '李荣浩', 32);
INSERT INTO `list` VALUES ('像鱼', 26, '王贰浪', 34);
INSERT INTO `list` VALUES ('多想在平庸的生活拥抱你 (Live)', 26, '隔壁老樊', 35);
INSERT INTO `list` VALUES ('牧马城市', 26, '毛不易· 《老男孩》电视剧片尾曲', 36);
INSERT INTO `list` VALUES ('时间的过客', 26, '名决', 37);
INSERT INTO `list` VALUES ('稻香', 26, '周杰伦', 38);
INSERT INTO `list` VALUES ('口是心非', 26, '杨小壮/鹏鹏', 39);
INSERT INTO `list` VALUES ('你的酒馆对我打了烊', 26, '陈雪凝', 40);
INSERT INTO `list` VALUES ('这一生关于你的风景', 26, '枯木逢春', 41);
INSERT INTO `list` VALUES ('野狼disco', 26, '宝石Gem', 42);
INSERT INTO `list` VALUES ('一个人挺好', 26, '孟颖', 43);
INSERT INTO `list` VALUES ('大眠 (Cover：王心凌)', 26, '王茗', 44);
INSERT INTO `list` VALUES ('给女孩（单曲）', 26, '李宇春', 45);
INSERT INTO `list` VALUES ('DJDJ给我一条K (抖音原版)', 26, '新旭', 49);
INSERT INTO `list` VALUES ('少年', 26, '梦然', 46);
INSERT INTO `list` VALUES ('泡沫', 26, 'G.E.M. 邓紫棋', 47);
INSERT INTO `list` VALUES ('退后', 26, '周杰伦', 48);
INSERT INTO `list` VALUES ('借 (Live)', 26, '毛不易', 50);
INSERT INTO `list` VALUES ('缘分一道桥', 26, '王力宏/谭维维· 《长城》电影片尾曲', 51);
INSERT INTO `list` VALUES ('我爱你', 26, '程jiajia', 52);
INSERT INTO `list` VALUES ('一生与你擦肩而过', 26, '阿悠悠', 54);
INSERT INTO `list` VALUES ('来自天堂的魔鬼', 26, 'G.E.M. 邓紫棋', 55);
INSERT INTO `list` VALUES ('说好不哭（with 五月天阿信）', 26, '周杰伦', 53);
INSERT INTO `list` VALUES ('告白气球', 26, '周杰伦', 56);
INSERT INTO `list` VALUES ('搁浅', 26, '周杰伦', 57);
INSERT INTO `list` VALUES ('我走后', 26, '小咪', 58);
INSERT INTO `list` VALUES ('一路向北', 26, '周杰伦· 《头文字D》电影插曲', 59);
INSERT INTO `list` VALUES ('黎明前的黑暗 (Live)', 26, '张韶涵/王晰', 60);
INSERT INTO `list` VALUES ('听妈妈的话', 26, '周杰伦', 61);
INSERT INTO `list` VALUES ('太阳 (正式版)', 26, '曲肖冰', 62);
INSERT INTO `list` VALUES ('绿色', 26, '陈雪凝', 63);
INSERT INTO `list` VALUES ('50 Feet (Explicit)', 26, 'SoMo', 65);
INSERT INTO `list` VALUES ('溯 (Reverse) feat. 马吟吟', 26, 'CORSAK胡梦周/马吟吟', 64);
INSERT INTO `list` VALUES ('你若三冬', 26, '阿悠悠', 66);
INSERT INTO `list` VALUES ('莫问归期', 26, '蒋雪儿', 67);
INSERT INTO `list` VALUES ('修炼爱情', 26, '林俊杰', 68);
INSERT INTO `list` VALUES ('云烟成雨', 26, '房东的猫· 《我是江小白》动画片尾曲', 71);
INSERT INTO `list` VALUES ('可不可以', 26, '张紫豪', 69);
INSERT INTO `list` VALUES ('等你下课 (with 杨瑞代)', 26, '周杰伦', 70);
INSERT INTO `list` VALUES ('心如止水', 26, 'Ice Paper', 72);
INSERT INTO `list` VALUES ('安和桥', 26, '宋冬野', 73);
INSERT INTO `list` VALUES ('画 (Live Piano Session Ⅱ)', 26, 'G.E.M. 邓紫棋', 74);
INSERT INTO `list` VALUES ('遇见', 26, '孙燕姿· 《向左走，向右走》电影主题曲', 75);
INSERT INTO `list` VALUES ('一个人挺好', 26, '杨小壮', 76);
INSERT INTO `list` VALUES ('Faded', 26, 'Alan Walker/Iselin Solheim', 77);
INSERT INTO `list` VALUES ('清新的小女孩', 26, 'July Tun', 78);
INSERT INTO `list` VALUES ('我的名字', 26, '焦迈奇', 79);
INSERT INTO `list` VALUES ('最美的伤口', 26, 'DJ小鱼儿', 80);
INSERT INTO `list` VALUES ('Last Dance', 26, '伍佰/China Blue', 82);
INSERT INTO `list` VALUES ('侧脸', 26, '于果', 81);
INSERT INTO `list` VALUES ('只要平凡', 26, '张杰/张碧晨· 《我不是药神》电影主题曲', 83);
INSERT INTO `list` VALUES ('你笑起来真好看', 26, '李昕融（ariel  li）/樊桐舟/李凯稠', 84);
INSERT INTO `list` VALUES ('给我一首歌的时间', 26, '周杰伦', 85);
INSERT INTO `list` VALUES ('酒醉的蝴蝶', 26, '崔伟立', 86);
INSERT INTO `list` VALUES ('可惜没如果', 26, '林俊杰· 《杜鹃之巢》韩剧中文主题曲|《对我而言，可爱的她》韩剧中文片尾曲', 87);
INSERT INTO `list` VALUES ('追光者', 26, '岑宁儿· 《夏至未至》电视剧插曲', 88);
INSERT INTO `list` VALUES ('夜空中最亮的星', 26, '逃跑计划', 89);
INSERT INTO `list` VALUES ('蒲公英的约定', 26, '周杰伦', 90);
INSERT INTO `list` VALUES ('演员', 26, '薛之谦', 91);
INSERT INTO `list` VALUES ('一曲相思', 26, '半阳', 92);
INSERT INTO `list` VALUES ('爱的飞行日记', 26, '周杰伦/杨瑞代', 93);
INSERT INTO `list` VALUES ('欧若拉', 26, '张韶涵', 95);
INSERT INTO `list` VALUES ('海阔天空', 26, 'BEYOND', 94);
INSERT INTO `list` VALUES ('大鱼', 26, '周深· 《大鱼海棠》动画电影印象曲', 96);
INSERT INTO `list` VALUES ('夜曲', 26, '周杰伦', 97);
INSERT INTO `list` VALUES ('山楂树の恋', 26, '程jiajia', 98);
INSERT INTO `list` VALUES ('青花瓷', 26, '周杰伦', 99);
INSERT INTO `list` VALUES ('시작 (开始)', 16, 'Gaho (가호)· 《梨泰院Class》韩剧插曲', 3);
INSERT INTO `list` VALUES ('TING TING TING with Oliver Heldens', 16, 'ITZY (있지)/Oliver Heldens', 4);
INSERT INTO `list` VALUES ('어떤 말도 (No Words)', 16, 'Crush (크러쉬)· 《梨泰院Class》韩剧插曲', 5);
INSERT INTO `list` VALUES ('꿈 (Boom) (梦)', 16, 'NCT 127 (엔씨티 127)', 6);
INSERT INTO `list` VALUES ('Sit Down!', 16, 'NCT 127 (엔씨티 127)', 7);
INSERT INTO `list` VALUES ('THAT’S A NO NO', 16, 'ITZY (있지)', 8);
INSERT INTO `list` VALUES ('NOBODY LIKE YOU', 16, 'ITZY (있지)', 9);
INSERT INTO `list` VALUES ('메아리 (Love Me Now) (回响)', 16, 'NCT 127 (엔씨티 127)', 11);
INSERT INTO `list` VALUES ('낮잠 (Pandora\'s Box) (午睡)', 16, 'NCT 127 (엔씨티 127)', 10);
INSERT INTO `list` VALUES ('YOU MAKE ME', 16, 'ITZY (있지)', 13);
INSERT INTO `list` VALUES ('Love The Moon (달을 사랑해)', 16, 'VIINI (권현빈)/李秀贤 (이수현)/BLOO (블루)', 12);
INSERT INTO `list` VALUES ('백야 (White Night) (白夜)', 16, 'NCT 127 (엔씨티 127)', 14);
INSERT INTO `list` VALUES ('뿔 (MAD DOG) (角)', 16, 'NCT 127 (엔씨티 127)', 15);
INSERT INTO `list` VALUES ('우산 (Love Song) (雨伞)', 16, 'NCT 127 (엔씨티 127)', 16);
INSERT INTO `list` VALUES ('24HRS', 16, 'ITZY (있지)', 17);
INSERT INTO `list` VALUES ('Day Dream (白日夢)', 16, 'NCT 127 (엔씨티 127)', 18);
INSERT INTO `list` VALUES ('FIESTA', 16, 'IZ*ONE (아이즈원)', 19);
INSERT INTO `list` VALUES ('Not Alone', 16, 'NCT 127 (엔씨티 127)', 20);
INSERT INTO `list` VALUES ('I DON’T WANNA DANCE', 16, 'ITZY (있지)', 21);
INSERT INTO `list` VALUES ('돌덩이 (Diamond)', 16, '河铉雨 (하현우)· 《梨泰院Class》韩剧插曲', 23);
INSERT INTO `list` VALUES ('Interlude: Neo Zone', 16, 'NCT 127 (엔씨티 127)', 22);
INSERT INTO `list` VALUES ('Dreams Come True', 16, 'NCT 127 (엔씨티 127)', 24);
INSERT INTO `list` VALUES ('솔직히 지친다 (Everybody Has)', 16, '金请夏 (김청하)', 25);
INSERT INTO `list` VALUES ('Psycho', 16, 'Red Velvet (레드벨벳)', 26);
INSERT INTO `list` VALUES ('My Bad (KSHMR Edit)', 16, 'SHAUN (숀)/어드밴스드 (Advanced)/Julie Bergan', 27);
INSERT INTO `list` VALUES ('Dreams Come True (Feat. Golden, Jay Park)', 16, 'CLUB 33 (KIRIN & SUMIN)/Golden/朴宰范 (박재범)', 28);
INSERT INTO `list` VALUES ('With Us', 16, 'VERIVERY (베리베리)· 《梨泰院Class》韩剧插曲', 29);
INSERT INTO `list` VALUES ('너를 사랑하고 있어 (MY LOVE)', 16, '伯贤 (백현)· 《浪漫医生金师傅2》韩剧插曲', 30);
INSERT INTO `list` VALUES ('그때 그 아인 (Someday, The Boy)', 16, '金弼 (김필)· 《梨泰院Class》韩剧插曲', 31);
INSERT INTO `list` VALUES ('너에게 난 나에게 넌 (You are to me I am to you)', 16, '郑恩地 (정은지)', 32);
INSERT INTO `list` VALUES ('RED MOON', 16, 'KARD (카드)', 35);
INSERT INTO `list` VALUES ('Sunrise Yellow', 16, 'FTISLAND (에프티 아일랜드)', 33);
INSERT INTO `list` VALUES ('Go away go away', 16, '灿烈 (찬열)/PUNCH (펀치)· 《浪漫医生金师傅2》韩剧插曲', 34);
INSERT INTO `list` VALUES ('AYAYAYA', 16, 'IZ*ONE (아이즈원)', 36);
INSERT INTO `list` VALUES ('달이 태양을 가릴 때 (Eclipse)', 16, '玟星 (문별)', 37);
INSERT INTO `list` VALUES ('Still Fighting It', 16, '이찬솔 (Lee Chan Sol)· 《梨泰院Class》韩剧插曲', 38);
INSERT INTO `list` VALUES ('다시 난, 여기 (Here I Am Again)', 16, '白艺潾 (백예린)· 《爱的迫降》韩剧插曲', 39);
INSERT INTO `list` VALUES ('Defence', 16, '박성일 (朴成一)/FRAKTAL· 《梨泰院Class》韩剧插曲', 40);
INSERT INTO `list` VALUES ('EYES', 16, 'IZ*ONE (아이즈원)', 41);
INSERT INTO `list` VALUES ('우린 친구뿐일까 (Maybe)', 16, 'Sondia (손디아)· 《梨泰院Class》韩剧插曲', 43);
INSERT INTO `list` VALUES ('SPACESHIP', 16, 'IZ*ONE (아이즈원)', 42);
INSERT INTO `list` VALUES ('우연인 듯 운명 (But it\'s Destiny)', 16, '10cm (십센치)· 《爱的迫降》韩剧插曲', 44);
INSERT INTO `list` VALUES ('바빠서 (Feat. 헤이즈) (Cold)', 16, '개코/Heize (헤이즈)', 45);
INSERT INTO `list` VALUES ('HARMONY', 16, '东海 (동해)/BewhY (비와이)', 47);
INSERT INTO `list` VALUES ('DREAMLIKE', 16, 'IZ*ONE (아이즈원)', 46);
INSERT INTO `list` VALUES ('HOME', 16, 'Yezi (예지)', 48);
INSERT INTO `list` VALUES ('둘만의 세상으로 가 (Let Us Go)', 16, 'Crush (크러쉬)· 《爱的迫降》韩剧插曲', 49);
INSERT INTO `list` VALUES ('노을 (Sunset)', 16, 'Davichi (다비치)· 《爱的迫降》韩剧插曲', 50);
INSERT INTO `list` VALUES ('내 마음의 사진 (Photo of My Mind)', 16, '宋佳人 (송가인)', 51);
INSERT INTO `list` VALUES ('Digital Lover', 16, 'Crush (크러쉬)', 53);
INSERT INTO `list` VALUES ('시그리스빌 (사랑의 불시착 Title Full Ver.)', 16, '金京熙 (김경희)· 《爱的迫降》韩剧插曲', 52);
INSERT INTO `list` VALUES ('You Make Me Back', 16, '김우성 (金佑星)·  《 梨泰院Class》韩剧插曲', 54);
INSERT INTO `list` VALUES ('Maybe', 16, 'Sondia (손디아)· 《梨泰院Class》韩剧插曲', 55);
INSERT INTO `list` VALUES ('Good Guy (Japanese ver.)', 16, 'SF9 (에스에프나인)', 57);
INSERT INTO `list` VALUES ('She Knows Everything', 16, '郑容和 (정용화)', 56);
INSERT INTO `list` VALUES ('별처럼 빛나는 시간 (Time, like a shining star)', 16, '朴智敏 (박지민)· 《你好 再见，妈妈！》韩剧插曲', 58);
INSERT INTO `list` VALUES ('WELCOME TO THE Y\'S CITY', 16, '郑容和 (정용화)', 60);
INSERT INTO `list` VALUES ('낯선날 (Weird Day)', 16, '玟星 (문별)/PUNCH (펀치)', 59);
INSERT INTO `list` VALUES ('버스 안에서 (On the bus)', 16, '장준/TAG/Kei (케이)', 61);
INSERT INTO `list` VALUES ('ONE&ONLY', 16, 'ASTRO (아스트로)', 62);
INSERT INTO `list` VALUES ('SEDANSOGU (세상에 단 하나뿐인 소중한 그대)', 16, 'SUHO (수호)', 63);
INSERT INTO `list` VALUES ('PAY DAY', 16, 'CHANGMO (창모)/ASH ISLAND/郑基高 (정기고)', 64);
INSERT INTO `list` VALUES ('SO CURIOUS', 16, 'IZ*ONE (아이즈원)', 65);
INSERT INTO `list` VALUES ('In & Out', 16, 'Red Velvet (레드벨벳)', 66);
INSERT INTO `list` VALUES ('그리움의 언덕 (The Hill of Yearning)', 16, 'April 2nd (에이프릴 세컨드)', 67);
INSERT INTO `list` VALUES ('우연인 듯 운명 (But it\'s Destiny)', 16, '10cm (십센치)· 《爱的迫降》韩剧插曲', 68);
INSERT INTO `list` VALUES ('자꾸 더 보고싶은 사람 (I Miss You)', 16, 'MAMAMOO (마마무)', 69);
INSERT INTO `list` VALUES ('HIP (Japanese ver.)', 16, 'MAMAMOO (마마무)', 70);
INSERT INTO `list` VALUES ('우리의 밤', 16, 'Sondia (손디아)', 71);
INSERT INTO `list` VALUES ('나의 모든 날 (All of My Days)', 16, '金世正 (세정)', 73);
INSERT INTO `list` VALUES ('HERE GOES NOTHING', 16, 'DPR LIVE (라이브)', 72);
INSERT INTO `list` VALUES ('언젠가 우리의 밤도 지나가겠죠 (SOMEDAY)', 16, 'IZ*ONE (아이즈원)', 75);
INSERT INTO `list` VALUES ('Dejavu (Prod. iDeal)', 16, 'BLNK/Simon Dominic (사이먼 도미닉)', 74);
INSERT INTO `list` VALUES ('노을 (Sunset)', 16, 'Davichi (다비치)· 《爱的迫降》韩剧插曲', 76);
INSERT INTO `list` VALUES ('GO BABY', 16, 'KARD (카드)', 77);
INSERT INTO `list` VALUES ('mirror', 16, '玟星 (문별)', 78);
INSERT INTO `list` VALUES ('다시 난, 여기 (Here I am Again)', 16, '白艺潾 (백예린)· 《爱的迫降》韩剧插曲', 79);
INSERT INTO `list` VALUES ('인간중독 (Feat. 유라 (youra)) (Prod. TOIL) (Human Addict)', 16, 'Leellamarz (릴러말즈)/TOIL/Youra (유라)', 80);
INSERT INTO `list` VALUES ('Nobody Knows', 16, '金润雅 (김윤아)· 《谤法》韩剧插曲', 81);
INSERT INTO `list` VALUES ('너의 하루는 좀 어때 (YOUR DAY)', 16, 'Gummy (거미)· 《浪漫医生金师傅2》韩剧插曲', 82);
INSERT INTO `list` VALUES ('우연이 아니야 (DESTINY)', 16, 'IZ*ONE (아이즈원)', 83);
INSERT INTO `list` VALUES ('ENEMY', 16, 'KARD (카드)', 85);
INSERT INTO `list` VALUES ('ILJIDO', 16, '玟星 (문별)', 84);
INSERT INTO `list` VALUES ('SWING', 16, 'TWICE (트와이스)', 87);
INSERT INTO `list` VALUES ('어떤 날엔 (Someday)', 16, '金在奂 (김재환)· 《爱的迫降》韩剧插曲', 86);
INSERT INTO `list` VALUES ('YOU & I', 16, 'IZ*ONE (아이즈원)', 88);
INSERT INTO `list` VALUES ('OPEN YOUR EYES', 16, 'IZ*ONE (아이즈원)', 89);
INSERT INTO `list` VALUES ('LEGACY', 16, 'DPR LIVE (라이브)', 92);
INSERT INTO `list` VALUES ('시행착오 (Trial and Error)', 16, 'DAVII (다비)/Babylon (베이빌론)/敏雅 (민아)', 90);
INSERT INTO `list` VALUES ('I Need You', 16, 'OVAN (오반)', 91);
INSERT INTO `list` VALUES ('PINK BLUSHER', 16, 'IZ*ONE (아이즈원)', 93);
INSERT INTO `list` VALUES ('나의 그대 (My Love)', 16, '金请夏 (김청하)', 94);
INSERT INTO `list` VALUES ('Summer Night In Heaven', 16, '郑容和 (정용화)', 95);
INSERT INTO `list` VALUES ('TO WHOEVER', 16, 'DPR LIVE (라이브)', 97);
INSERT INTO `list` VALUES ('형을 위한 노래 (Feat. 정혁) (The Song for My Brother)', 16, '南惠胜 (남혜승|Nam Hye Seung)/정혁/高恩静 (고은정)', 98);
INSERT INTO `list` VALUES ('어색한 사이', 16, '脸红的思春期 (볼빨간사춘기)/Vanilla Acoustic (바닐라 어쿠스틱)/Sweden Laundry (스웨덴세탁소)/Twenty Years (스무살)/Letter flow (레터 플로우)/金智秀 (김지수)/WH3N (웬)/Boramiyu (보라미유)/최유리', 96);
INSERT INTO `list` VALUES ('Asteroid', 16, 'IMLAY/刘扬扬', 99);

SET FOREIGN_KEY_CHECKS = 1;
